infra/realm/src/main/java/com/simprints/infra/realm/config/RealmConfig.kt
infra/realm/src/main/java/com/simprints/infra/realm/migration/RealmMigrations.kt
infra/realm/src/test/java/com/simprints/infra/realm/migration/RealmMigrationsTest.kt

- A crash occurred during the migration from 2022.2.8 to 2023.4.0 due to `Java. lang.IllegalStateException - [RLM_ERR_WRONG_TRANSACTION_STATE]: Must be in a write transaction. `There is no way to get a writable realm db during the migration.
-  Enable resolveEmbeddedObjectConstraints to delete orphan records because we can't delete them during the migration
-  I will test this change after merging this PR by migrating from 2022.2.8 to 2023.4.0. because it is tough to build old versions of SID using the new Android studio and JDk

[CORE-3159] Fix realm migration

---

feature/consent/src/main/res/layout/fragment_consent.xml

Buttons also will have the same height.

[CORE-3149] Buttons on the contest screen are filling the entire width of the screen

---

infra/auth-logic/src/main/java/com/simprints/infra/authlogic/authenticator/SignerManager.kt
infra/auth-logic/src/test/java/com/simprints/infra/authlogic/authenticator/SignerManagerTest.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/local/EnrolmentRecordLocalDataSourceImpl.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/local/EnrolmentRecordLocalDataSourceImplTest.kt

After using SID and then logging out, enrollment records remain in a database and captured images were remaining in app's internal folder (`/data/data/...`) in encrypted form.
Steps to reproduce:
1. Prepare SID for debugging to intercept the enrollment record DB key: at `com.simprints.infra.security.keyprovider.SecureLocalDbKeyProviderImpl` function `readRealmKeyFromSharedPrefs` result.
2. Build & install the debug variant of SID.
3. Clear app data.
4. Prepare a test project.
5. Sign in to the test project with the app.
6. Obtain the enrollment record DB key from step 1.
7. Convert the base64-formatted enrollment record DB key to hex.
8. Enroll a person with SID, using a calling app.
9. Open SID and sign out.
10. Pull `/data/data/com.simprints.id/files/images` folder from device.
11. Pull …

[CORE-3164] Fix for biometric data remaining on device after logout

---

fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt
infra/auth-logic/src/main/java/com/simprints/infra/authlogic/authenticator/Authenticator.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/migrations/ProjectConfigSharedPrefsMigration.kt
infra/config-sync/src/main/java/com/simprints/infra/config/sync/worker/ConfigurationWorker.kt
infra/core/src/main/java/com/simprints/core/workers/SimCoroutineWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/workers/EventDownSyncCountWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/workers/EventDownSyncDownloaderWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/workers/EventUpSyncCountWorker.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/up/workers/EventUpSyncUploaderWorkerTest.kt
infra/logging/src/main/java/com/simprints/infra/logging/LoggingConstants.kt
infra/logging/src/main/java/com/simprints/infra/logging/Simber.kt
infra/logging/src/test/java/com/simprints/infra/logging/SimberTest.kt
infra/logging/src/test/java/com/simprints/infra/logging/trees/AnalyticsTreeTest.kt
infra/logging/src/test/java/com/simprints/infra/logging/trees/CrashReportingTreeTest.kt

This started out with a benign notice of a log from production SID that Configuration worker's tag is incompatible with Firebase Analytics' limitations (see related ticket). Then I kept going into rabbit holes finding more and more instances where our logs didn't make it through to Firebase because they were either too long or contained invalid characters. As a result here are a few different changes:
- ConfigurationWorker's tag was renamed
- Some tags were also renamed (replacing spaces with underscores)
- Some worker logs were stripped of params since they were too long to fit
- Simber was updated to ensure that even if its users don't comply with the rules. In release/staging it makes the tags/messages valid by replacing or trimming the strings. In debug this throws an exception so we …

[CORE-3169] Comply with Firebase limitations for event names and messages length

---

README.md
build-logic/.gitignore
build-logic/convention/src/main/kotlin/PipelineDeployConventionPlugin.kt
build-logic/signing_properties.gradle.kts
ci/deployment/signing_properties_setup
ci/pipeline/setup

I renamed the signing_properties.gradle.kts so that Git ignores the new name and stops annoying us.
after merging this PR you should completely delete `signing_properties.gradle.kts  `and create a new file named `signing_info.gradle.kts` 
I will also open the same PR in the main branch to simplify your life.

Rename signing_properties.gradle so that it can be add the git ignore

---

gradle/libs.versions.toml
infra/auth-logic/src/main/java/com/simprints/infra/authlogic/authenticator/remote/UnauthenticatedClientFactory.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/network/SimApiClientFactory.kt
infra/network/build.gradle.kts
infra/network/src/main/java/com/simprints/infra/network/NetworkModule.kt
infra/network/src/main/java/com/simprints/infra/network/SimNetwork.kt
infra/network/src/main/java/com/simprints/infra/network/SimNetworkImpl.kt
infra/network/src/main/java/com/simprints/infra/network/apiclient/SimApiClientImpl.kt
infra/network/src/main/java/com/simprints/infra/network/httpclient/DefaultOkHttpClientBuilder.kt
infra/network/src/test/java/com/simprints/infra/network/SimNetworkImplTest.kt
infra/network/src/test/java/com/simprints/infra/network/apiclient/SimApiClientImplTest.kt
infra/network/src/test/java/com/simprints/infra/network/httpclient/DefaultOkHttpClientBuilderTest.kt

* ETag and related headers are working out of the box if the response cache is enabled in OkHttp
* Also slightly simplified network client creation with DI

CORE-3190 ETags and other request caches

---

.github/workflows/deploy-to-firebase-distribution.yml
.github/workflows/deploy-to-internal.yml
.github/workflows/deploy-to-staging.yml

- Cancel in-progress release builds when a new commit is pushed to the release branch
- Only run staging builds manually when needed

disable automated staging builds

---

feature/login/src/main/java/com/simprints/feature/login/screens/form/LoginFormFragment.kt
feature/login/src/main/java/com/simprints/feature/login/tools/play/GooglePlayServicesAvailabilityChecker.kt
feature/login/src/test/java/com/simprints/feature/login/tools/play/GooglePlayServicesAvailabilityCheckerTest.kt

The only remaining usage of deprecated onActivityResult() and onActivityResult() was for `GooglePlayServicesAvailabilityChecker` in `GoogleApiAvailability.showErrorDialogFragment`.
Updated to a newer variant of `GoogleApiAvailability.showErrorDialogFragment`, that uses `ActivityResultLauncher` instead.

[CORE-1022] Replace deprecated Apis startActivityForResult() and onActivityResult()

---

.github/dependabot.yml

Repositories from `settings.gradle.kts` `dependencyResolutionManagement` added as registries (see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#registries) in order to be recognizable by Dependabot.

[MS-26] Dependabot does not recognize Maven repositories in dependencyResolutionManagement - fix

---

build-logic/build_properties.gradle.kts

the unencrypted project secret can still work in 2023.4.0

Revert verion name

---

feature/login-check/src/main/java/com/simprints/feature/logincheck/LoginCheckViewModel.kt
feature/login-check/src/main/java/com/simprints/feature/logincheck/usecases/UpdateStoredUserIdUseCase.kt
feature/login-check/src/test/java/com/simprints/feature/logincheck/LoginCheckViewModelTest.kt
feature/login-check/src/test/java/com/simprints/feature/logincheck/usecases/UpdateStoredUserIdUseCaseTest.kt
infra/auth-logic/src/main/java/com/simprints/infra/authlogic/authenticator/Authenticator.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/AuthStore.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/AuthStoreImpl.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/domain/LoginInfoStore.kt
infra/auth-store/src/test/java/com/simprints/infra/authstore/AuthStoreImplTest.kt
infra/auth-store/src/test/java/com/simprints/infra/authstore/domain/LoginInfoStoreTest.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepository.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepositoryTest.kt

Main changes:
* Saving user ID on login
* If already logged in, save userID on successful login check when handling flow
This accidentally includes our fix in a separate PR from the hotfix.
Note on data "migration": 
* Until the user ID was deleted, it has been stored in the same shared prefs, so if a user updates from before the issue was introduced, the store will just reuse the old value as `TokenisableString.Raw`

MS-201 Save userId on login or intent

---

feature/matcher/src/main/java/com/simprints/matcher/usecases/MatchResultSet.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt
infra/auth-logic/src/main/java/com/simprints/infra/authlogic/authenticator/SignerManager.kt
infra/auth-logic/src/test/java/com/simprints/infra/authlogic/authenticator/SignerManagerTest.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/AuthStore.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/AuthStoreImpl.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/domain/LoginInfoStore.kt
infra/auth-store/src/test/java/com/simprints/infra/authstore/AuthStoreImplTest.kt
infra/auth-store/src/test/java/com/simprints/infra/authstore/domain/LoginInfoStoreTest.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/common/EventSyncCache.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/common/EventSyncCacheTest.kt
infra/orchestrator-data/src/main/java/com/simprints/infra/orchestration/data/results/AppResult.kt

* Switch LoginInfoStore to use encrypted shared prefs with data migration on the first data access.
* Some minor related cleanup - deleted redundant method in AuthStore/LoginInfoStore and deleted useless TODOs.
Note that this change adds a bit of startup time - on my Sony F8331 with Android 8 cold app start from launcher to dashboard changes from around 6-7s to 8-9s.

MA-11 Use secure shared prefs in login info store

---

.github/workflows/jira.yml

Disable jira-GitHub issues sync workflow until we set the correct webhook.

disable jira sync

---

infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/ApiUploadEventsBody.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/EventRemoteDataSource.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTask.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTask.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/EventRemoteDataSourceTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTaskTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTaskTest.kt
infra/events/src/debug/java/com/simprints/infra/events/sampledata/SampleDefaults.kt
infra/events/src/main/java/com/simprints/infra/events/EventRepository.kt
infra/events/src/main/java/com/simprints/infra/events/EventRepositoryImpl.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/EventLocalDataSource.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/EventRoomDao.kt
infra/events/src/test/java/com/simprints/infra/events/EventRepositoryImplTest.kt

Notable changes: 
* Added up-sync and down-sync type event scopes to the event up-sync task as a separate request.
* Changed the session event upload to happen in batches of arbitrary size (for now). This value should be reviewed and adjusted once we get more information.
* Added checks to only create request events with helpful information (e.g. skip down-sync attempts when there is nothing to sync). 
* Also, delete empty scopes on closing to even further reduce the amount of useless information to upload.

MS-42 Out-of-session event scope upload

---

feature/consent/src/main/java/com/simprints/feature/consent/screens/consent/helpers/AppendUtil.kt
feature/consent/src/main/java/com/simprints/feature/consent/screens/consent/helpers/GeneralConsentTextHelper.kt
feature/consent/src/main/java/com/simprints/feature/consent/screens/consent/helpers/ParentalConsentTextHelper.kt
feature/consent/src/test/java/com/simprints/feature/consent/screens/consent/helpers/AppendUtilKtTest.kt

`StringBuilder.appendSentence` available for `consent` package only.

[MS-216] Missing spaces between sentences in consent text fix - appendSentence extracted

---

.github/workflows/deploy-to-firebase-distribution.yml
.github/workflows/deploy-to-internal.yml
.github/workflows/jira.yml
.github/workflows/promote-artifact.yml
.github/workflows/refresh-gradle-cache.yml
.github/workflows/run-unit-tests.yml
.github/workflows/sonar-scan.yml

In case of issues with GitHub actions/jobs, they may get stuck and take all possible execution time, which is limited to 6 hours by default. A safer 30 minute limit String value is set in vars.JOB_TIMEOUT_MINUTES instead, and is converted to Int in the job configurations.

MS-233 GitHub Actions jobs execution time capped at vars.JOB_TIMEOUT_MINUTES

---

feature/dashboard/src/test/java/com/simprints/feature/dashboard/tools/di/FakeCoreModule.kt
id/src/main/java/com/simprints/id/Application.kt
infra/core/src/main/java/com/simprints/core/workers/SimCoroutineWorker.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncConstants.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncOrchestratorImpl.kt
infra/sync/src/main/java/com/simprints/infra/sync/enrolments/EnrolmentRecordWorker.kt
infra/sync/src/main/java/com/simprints/infra/sync/extensions/WorkManager.ext.kt
infra/sync/src/main/java/com/simprints/infra/sync/firmware/FirmwareFileUpdateWorker.kt
infra/sync/src/main/java/com/simprints/infra/sync/images/ImageUpSyncWorker.kt
infra/sync/src/test/java/com/simprints/infra/sync/SyncOrchestratorImplTest.kt

Main changes:
* Added a listener for event sync master worker state changes and cancel+reschedule image upload worker.
Things I learned in the process:
* `isStopped` flag in `CoroutineWorker` is completely useless. Cancelling the worker cancels the whole coroutine scope, and the code within the scope does not get a chance to check if it should stop 🤷🏻 
* Having foreground notification in a worker prevents if from being cancelled by the work manager. It also ignores the `isStopped` flag :D 
* Cancelling a periodic worker by ID seems to prevent future workers from being rescheduled, contrary to what the internet says.

MS-205 Image upload halt when event sync starts

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/steps/Step.kt
id/proguard-rules.pro

FSR the @Keep annotation doesn’t work and in release builds the result classes are obfuscated which prevents Jackson from properly (de)serializing them and without the step results Enrol Last Bio cannot work.
To reproduce - either use a prod version or a debug one with isMinifyEnabled = true . Then log into a project with “Duplicate biometric check enabled” set to true and try to do an Identification followed by Enrol Last Bio. In 2023.4.2 it fails with a gray screen saying that there was a duplicate (another issue we need to fix later).

[MS-241] Add -keep declarations for all classes saved in the OrchestratorCache

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt
infra/images/src/main/java/com/simprints/infra/images/model/Path.kt
infra/images/src/main/java/com/simprints/infra/images/model/SecuredImageRef.kt

`SecuredImageRef` was incorrectly obfuscated due to an erroneous import for annotation with the same name from a completely unrelated package.
PS. Ironically, the name of the package is "Google.ErrorProne.Annotations" :D

Apply correct Keep annotation for image ref and path models

---

feature/dashboard/src/test/java/com/simprints/feature/dashboard/main/sync/SyncViewModelTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImpl.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/migrations/models/OldProjectConfig.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/models/UpSynchronizationConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/ProjectConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/UpSynchronizationConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/remote/models/ApiSynchronizationConfiguration.kt
infra/config-store/src/main/proto/project_config.proto
infra/config-store/src/test/java/com/simprints/infra/config/store/local/migrations/ProjectConfigSharedPrefsMigrationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/models/ProjectConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/testtools/Models.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTask.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTaskTest.kt
infra/events/src/debug/java/com/simprints/infra/events/sampledata/EventFactoryUtils.kt
infra/events/src/main/java/com/simprints/infra/events/event/domain/models/upsync/EventUpSyncRequestEvent.kt
infra/sync/src/test/java/com/simprints/infra/sync/SyncOrchestratorImplTest.kt
infra/sync/src/test/java/com/simprints/infra/sync/config/testtools/Models.kt
infra/sync/src/test/java/com/simprints/infra/sync/config/usecase/RescheduleWorkersIfConfigChangedUseCaseTest.kt

Main changes:
* Added batch size configuration to `synchronization.up.simprints`. Defaulting all batch sizes to 1 if no config provided to mimic existing behaviour. 
* Using new configuration to upload events in the batches of provided sizes
* Split out-of-session events into separate request per scope to allow batching those events separately.

MS-229 Event upload batch size config

---

fingerprint/connect/src/main/java/com/simprints/fingerprint/connect/screens/controller/ConnectScannerControllerFragment.kt

View model is initialized only once in `ConnectScannerControllerFragment`. Flag responsible for asking the permission is persisted across the configuration changes

[MS-222] Rotation support for ConnectScannerControllerFragment 

---

feature/login/src/main/java/com/simprints/feature/login/screens/form/LoginFormFragment.kt
feature/login/src/main/java/com/simprints/feature/login/screens/form/LoginFormViewModel.kt
feature/login/src/main/java/com/simprints/feature/login/screens/form/SignInState.kt
feature/login/src/main/res/layout/fragment_login_form.xml
feature/login/src/main/res/layout/view_url_change_input.xml
feature/login/src/test/java/com/simprints/feature/login/screens/form/LoginFormViewModelTest.kt
infra/auth-store/src/main/java/com/simprints/infra/authstore/domain/LoginInfoStore.kt
infra/auth-store/src/test/java/com/simprints/infra/authstore/domain/LoginInfoStoreTest.kt
infra/network/src/main/java/com/simprints/infra/network/SimNetwork.kt
infra/network/src/main/java/com/simprints/infra/network/SimNetworkImpl.kt
infra/network/src/main/java/com/simprints/infra/network/url/BaseUrlProvider.kt
infra/network/src/main/java/com/simprints/infra/network/url/BaseUrlProviderImpl.kt
infra/network/src/test/java/com/simprints/infra/network/url/BaseUrlProviderImplTest.kt
infra/resources/src/main/res/color/input_text_background.xml
infra/resources/src/main/res/values/colors.xml
infra/resources/src/main/res/values/strings.xml
infra/resources/src/main/res/values/styles-widget.xml

Main changes: 
* Removed unnecessary "hide password" toggle for user ID field
* Made project ID field read-only
* Made disabled input fields more obviously disabled
* Moved QR project ID comparison to the one provided by intent to happen right after the scan
* Added an option to manually change the backend URL for cases when QR code cannot be used for the login (extreme edge case, but still a valid one)

MS-157 Login form updates

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorActivity.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorFragment.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/cache/OrchestratorCache.kt

Do not start any orchestration flows if there is one already executing.

Add a guard to prevent parallel flow execution

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorActivity.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorFragment.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/cache/OrchestratorCache.kt
infra/events/src/main/java/com/simprints/infra/events/EventRepositoryImpl.kt
infra/events/src/test/java/com/simprints/infra/events/EventRepositoryImplTest.kt

My understanding of the problem: 
* This only happened if several sessions were fired with unfortunate timing - the second session started processing around the time the first one got to the end of `UpdateProjectInCurrentSessionUseCase`. The timing is hard to estimate, but luckily I got a very slow device, and there is a 3-4 second window between intent firing and splash screen.
* Somehow, the new session manages to add a new `SessionCaptureEvent` with a new session ID and it gets stored in `EventRepository` event cache.
* At the same time previous session events are going through "read -> update labels -> write" sequence within the use case.
* But since the event in the cache has been changed, the session ID label in the updated events gets overwritten. Therefore we get …

Only add sessionId label to an event if it was previously empty

---

id/src/main/AndroidManifest.xml
id/src/main/java/com/simprints/id/services/sync/events/down/EventDownSyncResetService.kt
infra/core/src/main/java/com/simprints/core/workers/SimCoroutineWorker.kt

As documented [here ](https://developer.android.com/about/versions/14/changes/fgs-types-required#include-fgs-type-runtime) 
Calling `startForeground() ` without declaring the appropriate foreground service type permission, the system throws a SecurityException `InvalidForegroundServiceTypeException `

fix android.app.InvalidForegroundServiceTypeException in android 14

---

id/proguard-rules.pro

* Removed the rules that are not required anymore (fixed in the causing 3-rd party library)
* Use package wildcard to disable name obfuscation
* Use a slightly stricter rule for classes that extend marshallable content
Out of scope: I did not go through all annotation usage. It matters little for now and gives us a simpler way to roll back the rules if we find problems with the new setup.

MS-243 Simplify pro-guard rules

---

fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt
fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModelTest.kt
fingerprint/infra/base-bio-sdk/src/main/java/com/simprints/fingerprint/infra/basebiosdk/exceptions/BioSdkException.kt
fingerprint/infra/bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdk/BioSdkWrapper.kt
fingerprint/infra/bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdk/NECBioSdkWrapper.kt
fingerprint/infra/bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdk/SimprintsBioSdkWrapper.kt
fingerprint/infra/bio-sdk/src/test/java/com/simprints/fingerprint/infra/biosdk/NECBioSdkWrapperTest.kt
fingerprint/infra/bio-sdk/src/test/java/com/simprints/fingerprint/infra/biosdk/SimprintsBioSdkWrapperTest.kt
fingerprint/infra/nec-bio-sdk/src/main/java/com/simprints/fingerprint/infra/necsdkimpl/acquisition/template/FingerprintTemplateAcquisitionSettings.kt
fingerprint/infra/nec-bio-sdk/src/main/java/com/simprints/fingerprint/infra/necsdkimpl/acquisition/template/FingerprintTemplateProviderImpl.kt
fingerprint/infra/nec-bio-sdk/src/test/java/com/simprints/fingerprint/infra/necsdkimpl/acquisition/template/FingerprintTemplateProviderImplTest.kt
fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintCaptureWrapper.kt
fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintCaptureWrapperV1.kt
fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintCaptureWrapperV2.kt
fingerprint/infra/scanner/src/test/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintCaptureWrapperV1Test.kt
fingerprint/infra/scanner/src/test/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintCaptureWrapperV2Test.kt
fingerprint/infra/simprints-bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdkimpl/acquisition/template/FingerprintTemplateAcquisitionSettings.kt
fingerprint/infra/simprints-bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdkimpl/acquisition/template/FingerprintTemplateProviderImpl.kt
fingerprint/infra/simprints-bio-sdk/src/test/java/com/simprints/fingerprint/infra/biosdkimpl/acquisition/template/FingerPrintTemplateProviderImplTest.kt

- Save useless template extraction time in Vero2 only. 
- Skip Fingerprint Template Extraction for Low-Quality Images

[MS-271] Skip Fingerprint Template Extraction for Low-Quality Images

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/ExecutionTracker.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorActivity.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorModule.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/ExecutionTrackerTest.kt

ExecutionTracker now saves the 'currentLifecycleOwnerId' as a reference to the current main executing activity. All subsequent OrchestratorActivity instances will be finished if another one is executed.

MS-255 Adjust execution tracker to correctly restore the correct activity

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt

* `viewModelScope.launch {}` starts a concurrent coroutine, which can lead to a situation where the final app result is being created before saving of the `PersonCreationEvent` has fully finished, resulting in a "UNEXPECED_ERROR" response.
* This issue is "hidden" if the project has duplicate check enabled - save processes correctly while the match happens. Therefore to reproduce it, the project should be set up to return as soon as possible.

MS-334 Ensure there is no race condition in event saving and forming app result

---

.github/workflows/deploy-to-internal.yml

As we started to use the foreground services permission. We need an app bundle to be uploaded manually to Google Play.

Save app bundle in artifacts for manual uploads to google play

---

infra/events/src/main/java/com/simprints/infra/events/EventRepositoryImpl.kt
infra/events/src/test/java/com/simprints/infra/events/EventRepositoryImplTest.kt

Deleting sessions that were closed without setting the correct project ID. This happens when a session that starts before login is closed without successfully logging in.

MS-339 Unauthorised session fix

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/base/BaseFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/sync/LogoutSyncFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/syncdecline/LogoutSyncDeclineFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/main/sync/SyncFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/requestlogin/RequestLoginFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/about/AboutFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoFragment.kt

This simplifies things and should not impact the app, as the `::navigateSafely` was implemented to fix the orchestator's navigation issues

[MS-353] Reverting the Dashboard navigation back to the ::navigate invocation

---

infra/realm/src/main/java/com/simprints/infra/realm/RealmWrapperImpl.kt

If key is missing - create a new one and log the exception.

Handle exception when trying to obtain local DB key while creating Realm config

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/LogoutSyncViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/usecase/LogoutUseCase.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/main/sync/SyncViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/about/AboutViewModel.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/logout/LogoutSyncViewModelTest.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/logout/usecase/LogoutUseCaseTest.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/main/sync/SyncViewModelTest.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/about/AboutViewModelTest.kt

* The logout use case in the dashboard was fully executed in the background
* In some conditions, the main thread could crunch through several navigation events (logout fragment -> request login fragment -> main fragment) before the logout got to the clearing auth store.
* In this version, the auth clearing happens synchronously in the view model scope to ensure it is done before continuing with the navigation. Background work cancellation still happens asynchronously in the background after that.

MS-402 Prevent a navigation race condition on logout

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorFragment.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt

Initially, when the activity's process was killed (i.e. under load or with `Don't keep activities` flag turned on), the `ActionRequest` wasn't restored because the ViewModel was re-created.
This fix addresses this issue by saving the `ActionRequest` JSON in the `onSaveInstanceState`

[MS-405] Saving the Action Request in the bundle so it can survive the process death

---

face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/LiveFeedbackFragment.kt

Previously camera initialization was tied to fragment initialization which lead to issues when permission is not available straight away and/or when the user minimizes the app. This should now be resolved in addition to future-proofing the fragment for rotation.

[MS-412] Untie camera initialization from fragment initialization

---

infra/sync/src/main/java/com/simprints/infra/sync/config/worker/DeviceConfigDownSyncWorker.kt

The DeviceConfigDownSyncWorker can’t be started as it leaks the @HiltWorker annotation.
```
Could not instantiate com.simprints.infra.sync.config.worker.DeviceConfigDownSyncWorker
java.lang.NoSuchMethodException: com.simprints.infra.sync.config.worker.DeviceConfigDownSyncWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
at java.lang.Class.getConstructor0(Class.java:3325)
at java.lang.Class.getDeclaredConstructor(Class.java:3063)
at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:94)
at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:144)
at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
at …
```

[MS-417] Mark DeviceConfigDownSyncWorker as HiltWorker

---

infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/session/ApiEventScope.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/models/session/ApiEventScopeTest.kt

More info in the ticket. Opting for the much simpler solution to avoid more work and potential problems arising from changing the type of the field.

[MS-418] Don't include projectConfigurationUpdatedAt if it's empty

---

infra/core/src/main/java/com/simprints/core/workers/SimCoroutineWorker.kt

See Android foreground services documentation https://developer.android.com/develop/background-work/services/foreground-services#notification-immediate - clause 4.

[MS-422] Immediate foreground service type for preventing ForegroundServiceDidNotStartInTimeException

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt

Explicitly specifying the serialization modules within the `OrchestratorViewModel` so that `JsonHelper` knows how to unmarshal tokenization strings within the `ActionRequest`

[MS-405] Adding serialization modules when unmarshalling the actionRequest

---

infra/core/src/main/java/com/simprints/core/tools/utils/BatteryOptimizationUtils.kt
infra/core/src/main/java/com/simprints/core/workers/SimCoroutineWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/workers/EventDownSyncDownloaderWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/master/EventEndSyncReporterWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/master/EventStartSyncReporterWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/master/EventSyncMasterWorker.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/workers/EventUpSyncUploaderWorker.kt
infra/sync/src/main/java/com/simprints/infra/sync/config/worker/DeviceConfigDownSyncWorker.kt

A fix for some cases of uncaught `BackgroundServiceStartNotAllowedException`, before an improved solution is found.

[MS-368] Opting out of setting worker service foreground when battery optimization on

---

infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/EventRemoteDataSource.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/EventRemoteInterface.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/down/domain/EventDownSyncResult.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/up/domain/EventUpSyncResult.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTask.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTask.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/EventRemoteDataSourceTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTaskTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTaskTest.kt
infra/network/src/main/java/com/simprints/infra/network/httpclient/DefaultOkHttpClientBuilder.kt

Network interceptors cannot be reliably used in case of a network error (where the response is not available). Therefore it would be better to make the request IDs an explicit part of the business logic. 
This also limits the network request IDs to network calls where it is relevant (i.e. up-sync and down-sync)
Based on @ethiery branch from a while back.

MS-439 Move requestID logic from network interceptors to sync tasks

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorFragment.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/ShouldCreatePersonUseCase.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/response/CreateEnrolResponseUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/OrchestratorViewModelTest.kt
infra/images/src/main/java/com/simprints/infra/images/model/Path.kt
infra/orchestrator-data/build.gradle.kts
infra/orchestrator-data/src/main/java/com/simprints/infra/orchestration/data/ActionRequest.kt

The initial problem was [this crash](https://console.firebase.google.com/u/0/project/simprints-152315/crashlytics/app/android:com.simprints.id/issues/f4fd6e8c368b3fd2572a543a9f9721b3?time=last-thirty-days&types=crash&sessionEventKey=6638EB700306000139CB7542230944E9_1944343093486226798) that was caused by the Path class not being Serializable. 
However, after fixing that I found out that when OrchestratorActivity is killed, the VM is killed, too. In the VM's onCleared() we save the steps but we never load them when Activity/Fragment is restored. 
Fixing the above uncovered that we also need to restore the modalities, too.
Fixing the above uncovered that ActionRequest is not properly deserialized because it lacks subtype info.
IMO, we can improve the VM saving & restoration by unifying the …

Save & restore OrchestratorViewModel's data in case of Activity kill & restore

---

face/capture/src/main/java/com/simprints/face/capture/screens/FaceCaptureViewModel.kt
face/capture/src/test/java/com/simprints/face/capture/screens/FaceCaptureViewModelTest.kt
fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/extensions/SaveFingerprintImagesStrategy.kt
fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt
fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/extensions/SaveFingerprintImagesStrategyTest.kt
fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModelTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/migrations/models/OldProjectConfig.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/models/FaceConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/models/Vero2Configuration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/FaceConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/Vero2Configuration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/remote/models/ApiFaceConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/remote/models/ApiVero2Configuration.kt
infra/config-store/src/main/proto/project_config.proto
infra/config-store/src/test/java/com/simprints/infra/config/store/local/migrations/ProjectConfigSharedPrefsMigrationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/local/models/FaceConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/local/models/Vero2ConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/remote/models/ApiFaceConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/remote/models/ApiVero2ConfigurationTest.kt

Main changes:
* Existing `ONLY_GOOD_SCAN` saving strategy replaced by `ONLY_USED_IN_REFERENCE` since it is how it already works.
* Adding new logic for `ONLY_GOOD_SCAN` to extract only images with quality scores over the threshold.

MS-338 New image saving strategy

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorFragment.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt

When the device is rotated on the splash screen, it no longer leads to the flow disruption. 
https://github.com/Simprints/Android-Simprints-ID/assets/129499142/c2f32836-0367-482b-8d2b-812cda9a64f7

[MS-451] Splash screen rotation no longer leads to a freeze of the orchestration flow

---

face/capture/src/main/res/layout-land/fragment_confirmation.xml
face/capture/src/main/res/layout/fragment_confirmation.xml

The `Face has been successfully captured` was intentionally removed from the horizontal layout to provide more space for the image.
**Phone view**
**Tablet view**

[MS-468] Adding a separate horizontal fragment_confirmation.xml layout, so that the face capture screen elements won't overlap each other

---

fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt
fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/usecase/SaveImageUseCase.kt
fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModelTest.kt
fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/usecase/SaveImageUseCaseTest.kt
infra/images/build.gradle.kts
infra/images/src/main/java/com/simprints/infra/images/ImageRepository.kt
infra/images/src/main/java/com/simprints/infra/images/ImageRepositoryImpl.kt
infra/images/src/main/java/com/simprints/infra/images/ImagesModule.kt
infra/images/src/main/java/com/simprints/infra/images/metadata/ImageMetadataStore.kt
infra/images/src/main/java/com/simprints/infra/images/metadata/database/DbImageMetadata.kt
infra/images/src/main/java/com/simprints/infra/images/metadata/database/ImageMetadataDao.kt
infra/images/src/main/java/com/simprints/infra/images/metadata/database/ImageMetadataDatabase.kt
infra/images/src/main/java/com/simprints/infra/images/remote/ImageRemoteDataSource.kt
infra/images/src/main/java/com/simprints/infra/images/remote/ImageRemoteDataSourceImpl.kt
infra/images/src/test/java/com/simprints/infra/images/ImageRepositoryImplTest.kt
infra/images/src/test/java/com/simprints/infra/images/metadata/ImageMetadataStoreTest.kt
infra/images/src/test/java/com/simprints/infra/images/remote/ImageRemoteDataSourceImplTest.kt

Main changes:
* Added an option to add arbitrary key-value pairs for uploaded images.
* Metadata is stored in a Room table until the image upload happens.
This change targets the release branch since it was flagged as required as a hotfix for the current release. We should keep it open until 2024.1.0 is public and retarget to 2024.1.1. Although the effect on tested features is minimal, I would not be against releasing it now.

MS-337 Image metadata

---

face/capture/src/main/java/com/simprints/face/capture/FaceCaptureResult.kt
face/capture/src/main/java/com/simprints/face/capture/screens/FaceCaptureViewModel.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/CreatePersonEventUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/cache/OrchestratorCacheIntegrationTest.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/CreatePersonEventUseCaseTest.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/MapStepsForLastBiometricEnrolUseCaseTest.kt
fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/FingerprintCaptureResult.kt
fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/SubjectFactoryTest.kt

For historical reasons, the "PersonCreated" event data was collected as a combination of capture event IDs from the events in the database and captured templates in orchestrator step results.
In some erroneous edge cases, the capture data in step results and the database events might not match. Most likely, it was when one session was abruptly stopped, and another took its place (but that has to be proven). In any case, such mismatch causes invalid "PersonCreation" - one or more modalities do not have matching sets of capture reference IDs and event IDs.
This change ensures that the "CreatePerson" event has the correct sets of IDs since all the info comes only from step results. This does not address the edge case itself, but it at least makes it easier to recover the data. 
**Note**: …

MS-438 Prevent invalid person creation event

---

feature/matcher/src/main/java/com/simprints/matcher/usecases/MatchResultSet.kt

Matching algorithm provides a non-negative value, but the minimum lowest confidence value to compare it with was above 0. Adjusted to 0.

MS-471 Matching default lowest confidence value decreased to minimum possible

---

face/capture/src/main/java/com/simprints/face/capture/models/ScreenOrientation.kt
face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/FrameProcessor.kt
face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/LiveFeedbackFragment.kt
face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/LiveFeedbackFragmentViewModel.kt
face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/views/CameraTargetOverlay.kt
face/capture/src/main/res/layout-land/fragment_live_feedback.xml
face/capture/src/test/java/com/simprints/face/capture/models/ScreenOrientationTest.kt
face/capture/src/test/java/com/simprints/face/capture/screens/livefeedback/FrameProcessorTest.kt
face/capture/src/test/java/com/simprints/face/capture/screens/livefeedback/LiveFeedbackFragmentViewModelTest.kt

Due to historical reasons, the preview is formed around the guideline in the layout, whose height is defined as percentage of the screen height. It is hardcoded to 0.3 (30% of sceren height), and it doesn't work for the smaller horizontal dimensions. Thus, the new horizontal layout is introduced, that has a guideline set at the 0.5 (50% of screen height).

[MS-226] LiveFeedbackFragment now utilizes different layouts for horizontal and vertical screen orientations

---

infra/resources/src/main/res/values/strings.xml

The error is the same for invalid credentials and for Ending project status, but the error message was related only to the former - adjusted.

MS-421 Login error message adjusted to also make sense for an Ending project

---

feature/matcher/src/main/java/com/simprints/matcher/screen/MatchFragment.kt
feature/matcher/src/main/java/com/simprints/matcher/screen/MatchViewModel.kt
feature/matcher/src/main/res/layout/fragment_matcher.xml
feature/matcher/src/test/java/com/simprints/matcher/screen/MatchViewModelTest.kt
infra/core/src/main/java/com/simprints/core/tools/extentions/Context.ext.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSource.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/domain/models/BiometricDataSource.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/domain/models/BiometricDataSourceTest.kt
infra/resources/src/main/res/values/strings.xml

Notable changes:
* If the data source defines a custom permission it is checked at the start of the matching step. This may work for any future co-sync data sources.
* If permission is not granted, the user is forced to do a simplified "grant permission" flow on the matching step landing screen.
* "Grant permission" wording has been chosen to accommodate both possible request flows - just the dialogue and settings (when never ask again is selected). Although from my testing it seems that a single "Deny" would automatically set the "Never ask again" state.
https://github.com/Simprints/Android-Simprints-ID/assets/2182889/376d4805-a63a-4e66-b393-7edfdb7fa1ba
https://github.com/Simprints/Android-Simprints-ID/assets/2182889/c08d8191-ce10-4137-9e97-c171fb8b51a6

MS-199 co-sync data permission

---

id/proguard-rules.pro

Retrofit added rules to support for R8 full mode in version 2.10, which is why we didn't encounter any issues while testing version 2024.1.0. We downgraded to version 2.9 to resolve the Jackson issue, so we had to manually add the rules.

Add proguard rules to fix down sync

---

fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureFragment.kt

If the SDK licence is invalid the event live data is provided, but since it is not handled correctly, the user is stuck in a loop. Using the correct observer prevents repeated calls.

MS-278 Handle alert navigation only once on invalid licence

---

build-logic/convention/src/main/kotlin/common/SdkVersions.kt
feature/orchestrator/src/main/res/layout/activity_orchestrator.xml
id/src/main/AndroidManifest.xml
id/src/main/java/com/simprints/id/services/sync/events/down/EventDownSyncResetService.kt
infra/core/src/main/java/com/simprints/core/tools/extentions/Context.ext.kt

Notable changes:
* Increased target API to 35 (required updating some breaking changes in API)
* Added `onTimeout()` override to the only service we have to comply with the new requirement. The type of the reset service was also changed from `dataSync` to `shortSerivice` to avoid the new restrictions on sync services.

MS-472 Android 15 compatibility check

---

infra/license/src/main/java/com/simprints/infra/license/LicenseUtils.kt
infra/license/src/main/java/com/simprints/infra/license/local/LicenseLocalDataSourceImpl.kt
infra/license/src/main/java/com/simprints/infra/license/remote/ApiLicense.kt
infra/license/src/test/java/com/simprints/infra/license/LicenseUtilsTest.kt

The `BFSID` might return the face SDK license response with no `expiration` field:
```
{
"VENDOR": {
"vendor": "VENDOR",
"data": "{...}"
}
```
Reflecting this in the `License` class so that the parsing won't fail

[MS-537] The 'expiration' field in the 'License' class is now nullable to reflect the BFSID API

---

build-logic/convention/build.gradle.kts
build-logic/convention/src/main/kotlin/LibraryHiltConventionPlugin.kt
build-logic/convention/src/main/kotlin/LibraryProtobufConventionPlugin.kt
build-logic/convention/src/main/kotlin/LibraryRoomConventionPlugin.kt
build-logic/convention/src/main/kotlin/common/DependencyExt.kt
build-logic/convention/src/main/kotlin/common/KotlinAndroid.kt
build.gradle.kts
gradle/libs.versions.toml

Notable changes:
* Switching from KAPT to KSP allows fully utilising Kotlin 2.0.0 features (kapt automatically downgraded Kotlin to v1.9 on build time)
* It is now possible to run the IDE in K2 compiler mode and get minor improvements in compilation time. 
I tried some basic "benchmarking" (aka `gradlew clean` and `gradlew build` multiple times) and got the build time decrease from 60-90s to 45-60s. Although, the timing was very inconsistent.

MS-475 Enable K2 compiler

---

feature/validate-subject-pool/src/main/java/com/simprints/feature/validatepool/usecase/ShouldSuggestSyncUseCase.kt
feature/validate-subject-pool/src/test/java/com/simprints/feature/validatepool/usecase/ShouldSuggestSyncUseCaseTest.kt

Should be able to parse both "ISO" and "24h0m0s" format.

MS-554 Use more permissive method to parse maxAge duration

---

infra/sync/src/main/java/com/simprints/infra/sync/usecase/CleanupDeprecatedWorkersUseCase.kt

[[MS-567] Remove uploader and downloader from the deprecated workers](https://github.com/Simprints/Android-Simprints-ID/pull/785/commits/5d2079d55216738bc05ff53f9eeda3f858e2a5d5)
[MS-567]: https://simprints.atlassian.net/browse/MS-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MS-567-improve-sync

---

infra/events/src/main/java/com/simprints/infra/events/event/local/SessionScopeRoomDao.kt

I added a limit to the number of records uploaded to the backend to address the resource issue. This limit should be removed when the EventUpSyncTask is refactored to use resources more efficiently.

[MS-570] limit number of event Scopes

---

infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTask.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTask.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTaskTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTaskTest.kt

The `errorType` in `EventDownSyncRequestEvent` and `EventUpSyncRequestEvent` used to contain the stack trace, which was excessive for logging at the backend.

[MS-572] EventDownSyncRequest/EventUpSyncRequest events error type changed to just class name

---

feature/select-subject-age-group/src/main/java/com/simprints/feature/selectagegroup/screen/SelectSubjectAgeGroupFragment.kt

Add the missing handling for the exit form response when it is opened from the SelectSubjectAgeGroupFragment.

[MS-568] Handle exit form response in the SelectSubjectAgeGroupFragment

---

feature/exit-form/src/main/java/com/simprints/feature/exitform/screen/ExitFormFragment.kt
feature/exit-form/src/main/res/layout-land/fragment_exit_form.xml

[MS-562] Exit form is now optimized for the Landscape mode

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCaseTest.kt

'Validate ID Pool' step is only added if the `biometricDataSource` intent flag is resolved to `BiometricDataSource.Simprints`

[MS-576] 'Validate ID pool' step is added only when the biometric data source is "Simprints"

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCaseTest.kt

This fixed verification with co-sync, when the biometric data source is the data collection app.
Related fix for identification: https://github.com/Simprints/Android-Simprints-ID/pull/806

[MS-577] Fetching GUID for verification only when biometricDataSource is Simprints

---

.github/workflows/app-sweep.yml
.github/workflows/promote-artifact.yml

Auto-upload release APK to AppSweep server when moving build to Alpha track

[MS-531] AppSweep integration

---

build-logic/proguard-rules.pro
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
id/proguard-rules.pro

Due to inconsistencies between AGP, R8, KSP, and Hilt versions, we encountered issues when creating release builds. Over the last two days, I tried many workarounds mentioned in GitHub issues but found it safer to roll back. Downgrading the AGP version to the last known working version (in the release 2024.1.* branch) resolved the problem.
The error trace: 
```
error: ComponentProcessingStep was unable to process 'com.simprints.id.Application_HiltComponents.SingletonC' because 'com.simprints.infra.config.sync.ConfigManager' could not be resolved.
Dependency trace:
=> element (CLASS): com.simprints.infra.sync.config.worker.DeviceConfigDownSyncWorker
=> element (CONSTRUCTOR): DeviceConfigDownSyncWorker(android.content.Context,androidx.work.WorkerParameters,com.simprints.infra.config.sync.Con …
```

[MS-587] Resolve release compilation errors

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/mappers/request/validators/ConfirmIdentityValidator.kt

Since we cannot reproduce the issue from the current logs and the problem descriptions, it could be helpful to see what exact session ID values are being compared. 
If both are valid sessions we would be able to check the session events for extra clues.

Logging current and received session ID values before throwing exception

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/steps/Step.kt

* The app process is silently restarted when revoking permission in settings without calling `onCleared()` or any other indication within the view model. 
* This causes the VM recreation when navigating back to SID. Since the `onCleared()` has not been called there is nothing in the steps cache and the flow is forcibly closed on the next `handleResult()`/`doOnNextStep()` call. 
* The only way to be sure that the step cache is being preserved is to save the steps each time the flow proceeds to the next step or returns the final result. 
* Since the step list is always relatively short (less than 10 items) parsing to/from JSON should take a negligible amount of time. This could also make the cache and state restoration more consistent in other scenarios that involve navigating away from SID …

MS-593 Camera permission revokation fix

---

feature/validate-subject-pool/src/main/java/com/simprints/feature/validatepool/screen/ValidateSubjectPoolViewModel.kt
feature/validate-subject-pool/src/test/java/com/simprints/feature/validatepool/screen/ValidateSubjectPoolViewModelTest.kt

When running identification right after login and syncing candidates pool on request of the validation step, device rotation was causing incorrect sync state.

[MS-591] Fix for incorrect subject pool sync behavior after device rotation

---

face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/LiveFeedbackFragment.kt

Face capture camera viewfinder used to get stuck in its previous state after the app was put into background and then again into foreground.

[MS-592] Fix for face unable to be captured after app resumes from background

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/response/CreateVerifyResponseUseCase.kt

When a subject is enrolled using one SDK and then verified with another SDK (by selecting a different age group), SID returns an unexpected error. In this PR, I'm logging this matching issue as a non-fatal error until we implement the proper behavior for migrating between SDKs.

[MS-596] Log verification issue

---

feature/dashboard/src/main/res/layout/fragment_sync_info.xml

By default, ScrollView collapses content and does not expand when the content changes. This flag ensures that the view always matches screen size.

MS-606 Correctly display module list on sync info page

---

feature/matcher/src/main/java/com/simprints/matcher/screen/MatchFragment.kt

* `setupMatch()` calls `count()` on the enrolment record repository which also requires the permission in case of CommCare data source.

MS-614 Only call setupMatch after the permission is received

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/syncdecline/LogoutSyncDeclineFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/about/AboutFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/password/SettingsPasswordDialogFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/moduleselection/ModuleSelectionFragment.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/password/SettingsPasswordDialogFragmentTest.kt

* Custom constructors cannot be used by the system to restore the view state and instead cause the crash. 
* I could not figure out how to reliably unit-test the fragment with the new setup so the tests are disabled for now. We will have to rely on the manual test cases for the UI parts.

MS-671 Replace custom constructor with factory method in setting password dialog fragment

---

face/capture/build.gradle.kts
face/capture/src/main/java/com/simprints/face/capture/screens/FaceCaptureViewModel.kt
face/capture/src/test/java/com/simprints/face/capture/screens/FaceCaptureViewModelTest.kt
infra/license/src/main/java/com/simprints/infra/license/LicenseRepository.kt
infra/license/src/main/java/com/simprints/infra/license/LicenseRepositoryImpl.kt
infra/license/src/test/java/com/simprints/infra/license/repository/LicenseRepositoryImplTest.kt

* As described in JIRA and Slack - the face capture view model now attempts to refresh the license once if the cached license is invalid for some reason.

MS-407 Licence renewal if face SDK init fails

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/mappers/request/builders/ConfirmIdentifyRequestBuilder.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/request/requestFactories/ConfirmIdentityActionFactory.kt
feature/login-check/src/test/java/com/simprints/feature/logincheck/usecases/ActionFactory.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/steps/BuildMatcherSubjectQueryUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/ShouldCreatePersonUseCaseTest.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSource.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/domain/models/SubjectQuery.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSourceTest.kt
infra/orchestrator-data/src/main/java/com/simprints/infra/orchestration/data/ActionRequest.kt

* Added filtering of co-synced records from CommCare based on values in the subject query and data available in subjectActions to limit the 1:N/1:1 search only to relevant records.
* Additionally, added an option to provide caseId as a metadata field and pass this data as part of the subject query so that the co-sync data source could skip a case ID lookup.

MS-276 Respect subject query

---

fingerprint/connect/src/main/java/com/simprints/fingerprint/connect/screens/issues/nfcpair/NfcPairViewModel.kt
fingerprint/connect/src/test/java/com/simprints/fingerprint/connect/screens/issues/nfcpair/NfcPairViewModelTest.kt
fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/nfc/android/AndroidMifareUltralight.kt

Enhance the NFC error handling by catching `TagLostException `and `SecurityException` during NFC operations. Both exceptions can occur when the NFC tag moves out of range or a new tag is detected.

[MS-697] Ask the user to retry NFC pairing after the tag has left the field

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/mappers/request/IntentToActionMapper.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/request/IntentToActionMapperTest.kt
feature/orchestrator/src/main/AndroidManifest.xml

Inject last known session ID into CommCare intent extras if it is not present

MS-617 commcare session id fix

---

infra/events/src/main/java/com/simprints/infra/events/session/SessionEventRepositoryImpl.kt
infra/events/src/test/java/com/simprints/infra/events/session/SessionEventRepositoryImplTest.kt

Applying https://github.com/Simprints/Android-Simprints-ID/pull/851 to 2024.1.4 and creating 2024.1.5
PS Could not re-open old PR, so opening a new one.

MS-605 enrolment record created

---

face/infra/roc-v3/src/main/java/com/simprints/face/infra/rocv3/detection/RocV3Detector.kt

Benchmarks showed that the accurate method is not much slower while providing more consistency in timing.

MS-718 Use accurate face detection method from ROC v3

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/password/SettingsPasswordDialogFragment.kt
feature/dashboard/src/main/res/values/ids.xml
feature/dashboard/src/main/res/xml/preference_general.xml
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/SettingsViewModelTest.kt
infra/resources/src/main/res/values/strings.xml

* Added a button to request configuration update in the Settings screen (see screenshot)
* Update is locked under the settings password (if set in Vulcan)

MS-676 Sync config button

---

build-logic/proguard-rules.pro
id/proguard-rules.pro

This PR fixes the release build failure during ProGuard/R8 minification caused by Hilt-generated classes being stripped. The issue is unrelated to KSP, so I will revert the previous [PR ](https://github.com/Simprints/Android-Simprints-ID/pull/914)addressing KSP.

[MS-732] Fix ProGuard issue causing release build failure with Hilt modules

---

gradle/libs.versions.toml

This reverts commit 29eb051f0ae8a3e95f28945f80b8e32e162f5b9c.
Gradle 8.7 only works on a preview version of AS.

Revert "Bump android_gradlePlugin_version from 8.6.1 to 8.7.0"

---

build-logic/build_properties.gradle.kts
feature/login-check/src/test/java/com/simprints/feature/logincheck/usecases/UpdateSessionScopePayloadUseCaseTest.kt
infra/auth-logic/src/test/java/com/simprints/infra/authlogic/authenticator/ProjectAuthenticatorTest.kt
infra/auth-logic/src/test/java/com/simprints/infra/authlogic/authenticator/SignerManagerTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImpl.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/migrations/models/OldProjectConfig.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/models/ProjectConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/ProjectConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/remote/models/ApiProjectConfiguration.kt
infra/config-store/src/main/proto/project_config.proto
infra/config-store/src/test/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImplTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/remote/models/ApiProjectConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/testtools/Models.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/session/ApiEventScope.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/models/session/ApiEventScopeTest.kt
infra/events/src/debug/java/com/simprints/infra/events/sampledata/EventFactoryUtils.kt
infra/events/src/main/java/com/simprints/infra/events/EventRepositoryImpl.kt
infra/events/src/main/java/com/simprints/infra/events/event/domain/models/scope/EventScopePayload.kt
infra/sync/src/test/java/com/simprints/infra/sync/config/testtools/Models.kt

* Added ID field to the project configuration.
* Passing said ID when creating new session scopes.

MS-760 Project configuration ID

---

feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCaseTest.kt
infra/auth-logic/src/test/java/com/simprints/infra/authlogic/authenticator/ProjectAuthenticatorTest.kt
infra/auth-logic/src/test/java/com/simprints/infra/authlogic/authenticator/SignerManagerTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImpl.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/migrations/models/OldProjectConfig.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/models/ProjectConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/ExperimentalProjectConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/ProjectConfiguration.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/remote/models/ApiProjectConfiguration.kt
infra/config-store/src/main/proto/project_config.proto
infra/config-store/src/test/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImplTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/local/models/ProjectConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/models/ExperimentalProjectConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/remote/models/ApiProjectConfigurationTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/testtools/Models.kt
infra/sync/src/test/java/com/simprints/infra/sync/config/testtools/Models.kt

* Added a mechanism to handle dynamic custom/experimental config safely and explicitly.
* A custom configuration was added to validate ID pool only when required.

MS-765 Hide ID pool validation behind a flag

---

fingerprint/capture/src/main/res/layout-sw600dp-land/fragment_finger.xml
fingerprint/capture/src/main/res/layout-sw600dp-land/fragment_fingerprint_capture.xml

The tablets are big enough to display the same layout as in the 'layout' folder, so its content is just a copy-paste of these files.
Tablet:
Phone:

[MS-771] Adding 'layout-sw600dp-land' layout folder specifically for the tablets.

---

infra/events/src/main/java/com/simprints/infra/events/session/SessionEventRepositoryImpl.kt
infra/events/src/test/java/com/simprints/infra/events/session/SessionEventRepositoryImplTest.kt

* Added non-fatals to see logs around session creation and restoration
* Locked every event cache interaction with mutex to prevent any potential race condition

MS-755 Split session logging and mutex

---

infra/events/src/main/java/com/simprints/infra/events/session/SessionEventRepositoryImpl.kt

* Ensured that locked data is not accessed from within the already locked code block by explicitly separating synchronised and unsynchronised methods.
* Added an empty method scope to explicitly mark methods that should be called from locked context.

Fix deadlocks in session cache access

---

fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/screen/ObserveFingerprintScanStatusUseCaseTest.kt
fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintScanningStatusTracker.kt
fingerprint/infra/scanner/src/test/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintScanningStatusTrackerTest.kt

Changed `tryEmit` to `emit` in to ensure reliable state updates. `tryEmit` may drop updates under high concurrency or backpressure, while `emit` suspends until the emission completes, guaranteeing consistent delivery of state changes.

[MS-778] Switch from tryEmit to emit in FingerprintScanningStatusTracer

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/main/sync/SyncViewModel.kt

* If SID is open during project/device configuration sync on a compromised device, the project state may be requested after everything has been deleted. 
* To avoid large config manager and auth repo rework we can just consider the "non-reachable" project state as the project ending and force log out.

SM-782 Sync card crash fix

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModel.kt

* Removed pre-emptive refresh call on the view creation - it gets called on the first state update anyway.
* Tighten the sync completion check to prevent unnecessary calls.

MS-784 Removing redundant data refreshes

---

feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/cache/OrchestratorCacheTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/AgeGroup.kt

`AgeGroup` has an `isEmpty` method, which was unexpectedly serialized by Jackson, and is now explicitly excluded from serialization.
See https://stackoverflow.com/questions/69616587/why-does-jackson-add-an-empty-false-into-the-json
Credits to @BurningAXE for finding the root cause.

[MS-817] Fix for Jackson-caused unwanted attribute serialization in AgeGroup

---

fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt

The image quality tracking logic has been moved to execute after the image transfer is complete. This change addresses an issue where SID attempted to update the LEDs (green/red) during the image transfer process, causing conflicts.
As a result, the LEDs will now indicate quality (green/red) only after the transfer is finished. This is an acceptable trade-off since SID already provides clear signals to inform the user when to remove their finger, as well as when the scanner is idle or actively scanning.

[MS-824] Move image quality tracking to occur after image transfer

---

infra/resources/src/main/res/values/colors.xml

Brightness level for yellow Alert screen reduced by 25% to ease white text reading. This is the only use of the yellow color in the app.

[MS-816] Yellow alert screen background dimmed for better text readability

---

fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt

* Cancellation exception is expected when the task is cancelled, so no extra error handling is required - UI is automatically reset to a starting state.

MS-825 Ignore image transfer cancellation exception to avoid breaking user flow

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsViewModel.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/SettingsViewModelTest.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncOrchestrator.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncOrchestratorImpl.kt

* It only update the device state (compromised or not), which is not the intended use of the button.
* I noticed this while implementing MS-802, but it is not directly related to the task itself.

Refresh full project configuration when requested

---

feature/alert/build.gradle.kts
feature/alert/src/main/java/com/simprints/feature/alert/screen/AlertFragment.kt
feature/alert/src/main/java/com/simprints/feature/alert/screen/AlertViewModel.kt
feature/alert/src/main/res/layout/fragment_alert.xml
feature/alert/src/test/java/com/simprints/feature/alert/screen/AlertViewModelTest.kt
infra/resources/src/main/res/drawable/ic_copy.xml
infra/resources/src/main/res/values/strings.xml

Example of data exported to the clipboard:
```
Event ID:   229155a7-1588-408a-bf92-e2f16ac6ad8c
Timestamp:  1731597053343
Project ID: xRmp384ofU6dvylF1Hao
User ID:    Sergejs
Device ID:  d294a268b0d54f58
Session ID: c36ed54b-621c-47f3-845b-87d7b52c9e7f
Alert type: INVALID_SESSION_ID
```
[Figma design](https://www.figma.com/design/8gHXXZJkAhOnb2a7bm8llk/Simprints?node-id=2421-7265&node-type=canvas&t=jbo9t3dD22cG36A9-0)

MS-801 Add data export button to alert screen

---

feature/dashboard/src/main/AndroidManifest.xml
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/TroubleshootingPagerAdapter.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/OverviewFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/OverviewViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/usecase/CollectNetworkInformationUseCase.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/usecase/PingServerUseCase.kt
feature/dashboard/src/main/res/layout/fragment_troubleshooting_overview.xml
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/OverviewViewModelTest.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/usecase/PingServerUseCaseTest.kt
infra/network/src/main/java/com/simprints/infra/network/url/BaseUrlProvider.kt

* I added a section to the overview page instead of a separate page since the amount of information that we can reliably get from system services is not that large.
* Ping button requests the root of BFSID API. It is expected to return 404, but since the BFSID routing returns it, it is as good as any other endpoint to confirm that we can reach the backend.

MS-803 Network troubleshooting information

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/TroubleshootingPagerAdapter.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/workers/WorkerLogFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/workers/WorkerLogViewModel.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/troubleshooting/workers/WorkerLogViewModelTest.kt

* Basic list of work information provided directly from the Work Manager.

MS-806 Basic worker info log

---

face/capture/src/main/java/com/simprints/face/capture/screens/controller/FaceCaptureControllerFragment.kt
face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/LiveFeedbackFragment.kt
face/capture/src/main/java/com/simprints/face/capture/screens/preparation/PreparationFragment.kt
feature/consent/src/main/java/com/simprints/feature/consent/screens/consent/ConsentFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/base/BaseFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/sync/LogoutSyncFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/syncdecline/LogoutSyncDeclineFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/main/MainFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/main/sync/SyncFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/requestlogin/RequestLoginFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/about/AboutFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoFragment.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/main/sync/SyncFragmentTest.kt
feature/login/src/main/java/com/simprints/feature/login/screens/form/LoginFormFragment.kt
feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/TroubleshootingFragment.kt
feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/TroubleshootingViewModel.kt
feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/intents/IntentLogFragment.kt
feature/troubleshooting/src/test/java/com/simprints/feature/troubleshooting/TroubleshootingViewModelTest.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncConstants.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncOrchestratorImpl.kt
infra/ui-base/src/main/java/com/simprints/infra/uibase/navigation/NavigationResultExt.kt

* Fixed the incorrect "current" fragment in sync/main fragment. Also checked the rest of `navigateSafely()` calls to ensure that the provided fragment matches the one used in the graph.
* Fixed a related issue in the troubleshooting fragment in a bit more complex way. Fragments created as a part of the pager adapter do not have proper access to the "parent/root" fragment, so the navigation is done via the shared view model instead.
* Switched to navigation using "directions" where possible to add a layer of type safety for the basic app navigation.
As a bonus, I have found and fixed a minor issue with the project config not scheduling a one-time worker due to using the name of the periodic one.

MS-846 Safe navigation fixes

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/main/sync/SyncViewModel.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/ExecutionTracker.kt
feature/validate-subject-pool/src/main/java/com/simprints/feature/validatepool/usecase/ShouldSuggestSyncUseCase.kt
feature/validate-subject-pool/src/test/java/com/simprints/feature/validatepool/usecase/ShouldSuggestSyncUseCaseTest.kt
infra/core/src/main/java/com/simprints/core/tools/time/KronosTimeHelperImpl.kt
infra/core/src/main/java/com/simprints/core/tools/time/TimeHelper.kt
infra/core/src/test/java/com/simprints/core/tools/time/KronosTimeHelperImplTest.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManager.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManagerImpl.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/common/EventSyncCache.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/master/EventEndSyncReporterWorker.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/common/EventSyncCacheTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/master/EventEndSyncReporterWorkerTest.kt

* Replace the usage of the default `Date()` constructor with a Kronos timestamp to be consistent with other dates used in the sync process.
* Also check that we are not using the no-arg date constructor in other places.

MS-849 Do not use java date for "last sync" timestamp

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/debug/DebugFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/SettingsViewModel.kt
feature/dashboard/src/main/res/drawable/ic_config_update.xml
feature/dashboard/src/main/res/layout/fragment_debug.xml
feature/dashboard/src/main/res/layout/view_settings_update_config_item.xml
feature/dashboard/src/main/res/xml/preference_general.xml
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/SettingsViewModelTest.kt
feature/troubleshooting/build.gradle.kts
feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/overview/OverviewFragment.kt
feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/overview/OverviewViewModel.kt
feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/overview/usecase/CollectConfigurationDetailsUseCase.kt
feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/overview/usecase/CollectNetworkInformationUseCase.kt
feature/troubleshooting/src/main/res/layout/fragment_troubleshooting_overview.xml
feature/troubleshooting/src/test/java/com/simprints/feature/troubleshooting/overview/OverviewViewModelTest.kt
feature/troubleshooting/src/test/java/com/simprints/feature/troubleshooting/overview/usecase/CollectConfigurationDetailsUseCaseTest.kt
infra/config-sync/src/main/java/com/simprints/infra/config/sync/ConfigManager.kt
infra/config-sync/src/main/java/com/simprints/infra/config/sync/ConfigSyncCache.kt
infra/config-sync/src/test/java/com/simprints/infra/config/sync/ConfigManagerTest.kt
infra/config-sync/src/test/java/com/simprints/infra/config/sync/ConfigSyncCacheTest.kt
infra/resources/src/main/res/values/strings.xml
infra/sync/src/main/java/com/simprints/infra/sync/SyncOrchestrator.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncOrchestratorImpl.kt
infra/sync/src/test/java/com/simprints/infra/sync/SyncOrchestratorImplTest.kt

As per updated requirements:
* Added refresh icon (see video below).
* Added a toast notification after both sync workers finish. Since "start" and "end" toasts were shown way too quickly, I decided to change the description text under the preference instead of the "starting" toast (see video below).
* I added a subtitle with the time since the "last update." It is in relative format to keep it consistent with the "last sync" indicator.
https://github.com/user-attachments/assets/48f0b347-b75b-4eb9-9d1a-544d621f4b7e
* As a bonus, I have also added some details about the current configuration to the troubleshooting overview - config ID, config update data (in vulcan) and time since last config sync.

MS-676 Sync config button upgrades

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/mappers/response/LibSimprintsResponseMapper.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/response/CommCareResponseMapperTest.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/response/LibSimprintsResponseMapperTest.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/response/OdkResponseMapperTest.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/AddCallbackEventUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/AddCallbackEventUseCaseTest.kt
gradle/libs.versions.toml
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/ApiTier.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/callback/ApiCallbackComparisonScore.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/EventValidationUtils.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/models/callback/ApiCallbackComparisonScoreTest.kt
infra/events/src/debug/java/com/simprints/infra/events/sampledata/EventFactoryUtils.kt
infra/events/src/main/java/com/simprints/infra/events/event/domain/models/callback/CallbackComparisonScore.kt
infra/events/src/test/java/com/simprints/infra/events/event/domain/models/EventPayloadTest.kt
infra/events/src/test/java/com/simprints/infra/events/event/domain/models/callback/IdentificationCallbackEventTest.kt
infra/events/src/test/java/com/simprints/infra/events/event/domain/models/callback/VerificationCallbackEventTest.kt
infra/orchestrator-data/src/main/java/com/simprints/infra/orchestration/data/responses/AppMatchResult.kt
infra/orchestrator-data/src/test/java/com/simprints/infra/orchestration/data/responses/AppMatchResultTest.kt

* Removed hardcoded tier definitions and values passed around in match result data classes.
* For backwards compatibility tier is being mapped from a match quality (high->tier1, medium->tier2, low->tier3, none->tier4).
A small note on `ApiTier` changes - it is currently implemented on an educated assumption of how the cloud team will update the request body schema and versions.

MS-764 Tier deprecation in SID responses

---

.github/workflows/deploy-dev-workflow.yml
.github/workflows/deploy-main-workflow.yml
.github/workflows/reusable-build-apk.yml
.github/workflows/reusable-deploy-to-firebase-distribution.yml

Context: https://simprints.slack.com/archives/GAW460V19/p1736868512985299
This PR 
1) Fixes a bug "referencing github.run_number directly in a reusable workflow’s expression (if:), which the Actions parser doesn’t allow at parse time."
2) Adds the deployment URL to the summary page so people don't dig into the steps console to get it.

Fix github action oddity that prevents parsing github vars in reusable workflows + Add deploy URL to Summary Page 

---

fingerprint/connect/src/main/java/com/simprints/fingerprint/connect/screens/issues/serialentrypair/SerialEntryPairFragment.kt

This issue was considered fixed but continues to happen from time to time on all versions (including 2024.2.2).
Looks like there's more than one path to it - probably some async stuff that's hard to debug. So I just added protection to avoid crashing when we don't need to update the UI anyway.

[CORE-3132] Add protection to avoid trying to access view when it's null

---

.github/workflows/pipeline-deploy-to-dev.yml
.github/workflows/pipeline-deploy-to-internal.yml
.github/workflows/pipeline-deploy-to-staging.yml
.github/workflows/reusable-build-apk.yml
.github/workflows/reusable-get-version-name.yml
build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt

update the workflow to dynamically get the version name based on the type of build. This is needed because for debug version the version name is not available in the branch name. 
(I will squash on merge :-D)

update debug version name

---

fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt
fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModelTest.kt
fingerprint/infra/bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdk/BioSdkWrapper.kt
fingerprint/infra/bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdk/NECBioSdkWrapper.kt
fingerprint/infra/bio-sdk/src/main/java/com/simprints/fingerprint/infra/biosdk/SimprintsBioSdkWrapper.kt
fingerprint/infra/bio-sdk/src/test/java/com/simprints/fingerprint/infra/biosdk/NECBioSdkWrapperTest.kt
fingerprint/infra/bio-sdk/src/test/java/com/simprints/fingerprint/infra/biosdk/SimprintsBioSdkWrapperTest.kt

This PR configures the minimum number of good scans and new finger addition rules based on the active SDK via BioSdkWrapper.
- Set TARGET_NUMBER_OF_GOOD_SCANS:
SimMatcher: 2 good scans.
NEC: 0 good scans.
- Control new finger on bad scans:
SimMatcher: Allowed.
NEC: Disabled.
- Removed hardcoded values from FingerprintCaptureViewModel.
Why?
- NEC is used for toddlers, who typically have higher bad scan rates. The current setup in the GT project prevents adding new fingers when there are too many bad scans.
- No change in behavior for SimMatcher; only NEC is adjusted.

[MS-865] Configure good scans and adding new finger rules via BioSdkWrapper

---

face/infra/bio-sdk-resolver/src/main/java/com/simprints/face/infra/biosdkresolver/ResolveFaceBioSdkUseCase.kt
face/infra/bio-sdk-resolver/src/test/java/ResolveFaceBioSdkUseCaseTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/ConfigStoreModule.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/migrations/ProjectConfigFaceEmptyVersionMigration.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/local/migrations/ProjectConfigFaceEmptyVersionMigrationTest.kt

Migrated face configurations now default to ROC V1 SDK version 1.23. Additionally, the FaceBioSDK resolver ensures a non-empty version is present.

[MS-920] Set ROC V1 as default FaceBioSDK version for migrated configs

---

infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTask.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTaskTest.kt

This is the simple fix that touches the least amount of code and leaves the complexity as is.
Check out #1077 for the refactored version.
Pros
- Lessens risk that we break something now
Cons
- Increases risk we break something in the future 
- Code remains complex and hard to reason about

Ms 861 fix bug in module downsync when moves are involved

---

face/capture/src/main/java/com/simprints/face/capture/screens/livefeedbackautocapture/LiveFeedbackAutoCaptureFragment.kt
face/capture/src/main/java/com/simprints/face/capture/screens/livefeedbackautocapture/LiveFeedbackAutoCaptureFragmentViewModel.kt
face/capture/src/test/java/com/simprints/face/capture/screens/livefeedbackautocapture/LiveFeedbackAutoCaptureFragmentViewModelTest.kt
infra/resources/src/main/res/values/strings.xml

When using auto-capture and starting the viewfinder, the start of the "sensing" for the qualifying quality face presense in the frame was delayed for 2 seconds.
When using auto-capture and starting the viewfinder, the start of the "sensing" for the qualifying quality face presense in the frame is delayed until the user taps the "Start capture" button.

[MS-972] Start Capture button to manually prepare for Face Auto-Capture

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/moduleselection/repository/ModuleRepositoryImpl.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModelTest.kt
feature/matcher/build.gradle.kts
feature/matcher/src/main/java/com/simprints/matcher/screen/MatchViewModel.kt
feature/matcher/src/main/java/com/simprints/matcher/usecases/FaceMatcherUseCase.kt
feature/matcher/src/main/java/com/simprints/matcher/usecases/FingerprintMatcherUseCase.kt
feature/matcher/src/main/java/com/simprints/matcher/usecases/MatcherUseCase.kt
feature/matcher/src/test/java/com/simprints/matcher/screen/MatchViewModelTest.kt
feature/matcher/src/test/java/com/simprints/matcher/usecases/FaceMatcherUseCaseTest.kt
feature/matcher/src/test/java/com/simprints/matcher/usecases/FingerprintMatcherUseCaseTest.kt
feature/matcher/src/test/java/com/simprints/matcher/usecases/SaveMatchEventUseCaseTest.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/steps/BuildMatcherSubjectQueryUseCase.kt
feature/validate-subject-pool/src/main/java/com/simprints/feature/validatepool/usecase/IsModuleIdNotSyncedUseCase.kt
feature/validate-subject-pool/src/test/java/com/simprints/feature/validatepool/screen/ValidateSubjectPoolViewModelTest.kt
feature/validate-subject-pool/src/test/java/com/simprints/feature/validatepool/usecase/IsModuleIdNotSyncedUseCaseTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/tokenization/TokenizationProcessor.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/EnrolmentRecordRepository.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/EnrolmentRecordRepositoryImpl.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/EnrolmentRecordsStoreModule.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/IdentityDataSource.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSource.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/domain/models/SubjectQuery.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/local/EnrolmentRecordLocalDataSourceImpl.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/usecases/CompareImplicitTokenizedStringsUseCase.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/usecases/CompareTokenizedStringsUseCase.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/EnrolmentRecordRepositoryImplTest.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSourceTest.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/local/EnrolmentRecordLocalDataSourceImplTest.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/usecases/CompareImplicitTokenizedStringsUseCaseTest.kt

Given that the plain string values might be both tokenized or untokenized, we need some mechanism that properly compares the values in the `CommCareIdentityDataSource`.
The `CompareImplicitTokenizedStringsUseCase` is added to check is the implicitly tokenized values are the same. Implicitly tokenized means that the plain string value can be both tokenized and untokenized, and we have no additional information that specifies the tokenization state. 
The use case operates using the following logic:
- Checks if the values are already similar
- If not, then tries to tokenize both values so that each of them is wrapped into `TokenizableString.Tokenized` class. It tries to decrypt each string using the project tokenization keys. If successful, then the string is already tokenized. If not, it …

[MS-852] Tokenizable fields from CommCare response are now properly filtered

---

feature/enrol-last-biometric/src/main/java/com/simprints/feature/enrollast/screen/EnrolLastBiometricViewModel.kt
feature/enrol-last-biometric/src/test/java/com/simprints/feature/enrollast/screen/EnrolLastBiometricViewModelTest.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/response/AppResponseBuilderUseCase.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/response/CreateEnrolResponseUseCase.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/response/EnrolSubjectUseCase.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/OrchestratorViewModelTest.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/response/AppResponseBuilderUseCaseTest.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/response/CreateEnrolResponseUseCaseTest.kt
feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/response/EnrolSubjectUseCaseTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/ConfigRepositoryImpl.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImpl.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/ConfigRepositoryImplTest.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImplTest.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/EnrolmentRecordRepositoryImpl.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/local/EnrolmentRecordLocalDataSource.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/local/EnrolmentRecordLocalDataSourceImpl.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/EnrolmentRecordRepositoryImplTest.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/local/EnrolmentRecordLocalDataSourceImplTest.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManagerImpl.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTask.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/workers/EventDownSyncDownloaderWorker.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/EventSyncManagerTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/EventDownSyncTaskTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/workers/EventDownSyncDownloaderWorkerTest.kt

If the enrolment callout is made when there is no authentication in SID, then the `moduleId` and `attendantId` remain untokenized in the local database. Any further verification and identification request will have their `moduleId` tokenized, meaning that the initial enrolment will never be fetched from the local database, since its `moduleId` is untokenized.
- No SID auth
- Enrolment request is sent to SID with `moduleId` = `123`
- No tokenization keys are available at the moment of the event and subject creation, thus all the data from the request is saved with `moduleId` = `123`
- SID authenticates, tokenization keys become available, enrolment flow ends, data is saved in the local database
- Identification request is sent to SID with `moduleId` = `123`
- Since the tokenization keys …

[MS-721] Investigate what cause first enrolment to be unidentifiable on this specific project

---

.github/workflows/reusable-sonar-scan.yml

This is the first time scanning release branches before generating a release build. SonarQube defaults to the main branch if the branch name is not provided.

send branch name to SonarQube to correctly identify release branches

---

.github/workflows/pipeline-deploy-to-internal.yml

The child workflows should be called with `secrets: inherit` to enable access to secret variables.

Secrets inherit

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/usecases/GetEnrolmentCreationEventForSubjectUseCase.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/usecases/GetEnrolmentCreationEventForSubjectUseCaseTest.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSource.kt
infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/usecases/CompareImplicitTokenizedStringsUseCase.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/usecases/CompareImplicitTokenizedStringsUseCaseTest.kt

1. Added the concrete class type (Raw or Tokenized) to tokenizable fields returned to CoSync
2. Given this - optimized CompareImplicitTokenizedStringsUseCase to only probe the tokenization state of TokenizableString.Raw values since if a value is TokenizableString.Tokenized we know its class was explicitly specified and can be sure of its tokenization state

[MS-852] Add explicit class type to the tokenizable fields returned to CoSync

---

face/capture/src/main/java/com/simprints/face/capture/screens/FaceCaptureViewModel.kt
face/capture/src/test/java/com/simprints/face/capture/screens/FaceCaptureViewModelTest.kt

* Face capture fragment was doing a licence check on every screen opening. 
* This causes an unnecessary event when opening the refusal form and returning back to capture.
* A similar mechanism was already in place for the fingerprint capture screen.

MS-886 Unnecessary licence checks

---

infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSource.kt
infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSourceTest.kt

There was a bug in the identification callouts from CommCare due to incorrect filtering logic in CommCareIdentityDataSource. The filtering logic was unintentionally excluding all records, causing identification failures.
The issue arose when building the subjectQuery in BuildMatcherSubjectQueryUseCase, where the filtering logic failed under different partitionType conditions:
partitionType = PROJECT → Both module ID and attendant ID are null.
partitionType = USER → The module ID in the query is null.
partitionType = MODULE → The attendant ID is null in the query.
Due to this, the filtering logic always failed, as it did not account for null values correctly.
I updated the filtering logic to correctly handle null values to ensure that valid records are no longer filtered out incorrectly.

[MS-887] Fix Filtering Logic in CommCareIdentityDataSource 

---

infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSource.kt
infra/events/src/main/java/com/simprints/infra/events/event/cosync/CoSyncEnrolmentRecordCreationEventDeserializer.kt
infra/events/src/test/java/com/simprints/infra/events/event/cosync/CoSyncEnrolmentRecordCreationEventDeserializerTest.kt

When using CoSync as data source SID fails to parse enrolments made with version < 2023.3.3 (first version that introduces tokenization). This is because in older versions `moduleId` and `attendantId` in `EnrolmentRecordCreationPayload` were plain `String`s instead of `TokenizableString`s.

[MS-894] Add a custom CoSync deserializer that accounts for past versions of EnrolmentRecordCreationEvent

---

feature/matcher/src/main/java/com/simprints/matcher/screen/MatchViewModel.kt

The `MatchViewModel` observes the `LoadingCandidates` event from the Matcher UseCase and emits it to the LiveData's Observer. The `LoadingCandidates` event that might be emitted multiple times a second. 
We've observed that the UI layer processed less than 5% of the events sent to the LiveData:
- `43819` events emitted by the Use Case
- `43819` events forwarded to the LiveData by the ViewModel (0% loss)
- `2372` - received by the observer (`MatchFragment`, >90% loss)
Not only the events were being lost, the Observer stopped receiving them after some arbitrary threshold - after ~20 events on some devices, ~4000 events on others.
It was identified that by removing the state reference to itself for update, the issue disappears.
```
MatcherUseCase.MatcherState.CandidateLoaded -> { …
```

[MS-923] Adding internal counter for the amount of loaded candidates in the MatchViewModel

---

infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTask.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/workers/EventUpSyncUploaderWorker.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/up/workers/EventUpSyncUploaderWorkerTest.kt
infra/events/src/main/java/com/simprints/infra/events/EventRepository.kt
infra/events/src/main/java/com/simprints/infra/events/EventRepositoryImpl.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/EventLocalDataSource.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/EventRoomDao.kt
infra/events/src/test/java/com/simprints/infra/events/EventRepositoryImplTest.kt
infra/events/src/test/java/com/simprints/infra/events/event/local/EventLocalDataSourceTest.kt

Fixed two different issues that messed up up-sync event count reporting:
* We counted all events for the max value, which included the events from open sessions and caused the total to be slightly inflated. One simple join removes this issue - now we only count the events that are actually going to be uploaded.
* Events in the last uploaded scope were counted twice due to "COMPLETE" state carrying the count from the last "RUNNING" state in the up sync task, this caused the progress count to overshoot the "max" (sometimes by significant amounts): 
```
I Started
D Received {"type":"EventUpSyncScope$ProjectScope","projectId":"xRmp384ofU6dvylF1Hao","operation":{"projectId":"xRmp384ofU6dvylF1Hao","lastState":"COMPLETE","lastSyncTime":1741169379383,"uniqueKey":"c96f77da-46c9-3791-a207-089c37d1b1 …
```

MS926 Upload count fixes

---

.github/PULL_REQUEST_TEMPLATE/bugfix_pr.md
.github/PULL_REQUEST_TEMPLATE/feature_pr.md

[JIRA ticket](https://simprints.atlassian.net/browse/MS-673 )
Will be released in: **N/A**
* Adding PR template for new features and bug fixes to standardise the PR creation process.

SM-673 Add basic PR templates

---

infra/network/src/main/java/com/simprints/infra/network/SimNetworkImpl.kt
infra/network/src/main/java/com/simprints/infra/network/apiclient/SimApiClientImpl.kt
infra/network/src/main/java/com/simprints/infra/network/httpclient/BuildOkHttpClientUseCase.kt
infra/network/src/test/java/com/simprints/infra/network/SimNetworkImplTest.kt
infra/network/src/test/java/com/simprints/infra/network/apiclient/SimApiClientImplTest.kt
infra/network/src/test/java/com/simprints/infra/network/httpclient/BuildOkHttpClientUseCaseTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-934)
Will be released in:  2025.2.0
First known affected version:From the moment we started using OkHttp 
The issue was identified through [this](https://console.firebase.google.com/project/simprints-152315/crashlytics/app/android:com.simprints.id/issues/9f70fa04d60773d9576c0a1c4381e56a?utm_campaign=extensions&utm_medium=SLACK&utm_source=NEW_ISSUE)  Crashlytics OOM error, revealing that OkHttp had created 300 threads. After reviewing the OkHttp [documentation](https://square.github.io/okhttp/5.x/okhttp/okhttp3/-ok-http-client/index.html), I discovered that SID was incorrectly creating a new `OkHttpClient` instance for each API call instead of reusing a single instance.
- Reuses `OkHttpClient` for identical auth tokens, reducing …

improve OkHttpClient reuse & efficiency

---

infra/events/src/main/java/com/simprints/infra/events/event/local/EventDatabaseFactory.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/EventLocalDataSource.kt
infra/events/src/test/java/com/simprints/infra/events/event/local/EventDatabaseFactoryTest.kt
infra/events/src/test/java/com/simprints/infra/events/event/local/EventLocalDataSourceTest.kt

[MS-936 ](https://simprints.atlassian.net/browse/MS-936)
First known affected version: **it is happing in all versions 
As seen in the bug ticket and [Crashlytics](https://console.firebase.google.com/project/simprints-152315/crashlytics/app/android:com.simprints.id/issues/1e397ff40fcf20f006fc93041dc683da?utm_campaign=extensions&utm_medium=JIRA&utm_source=CRASHLYTICS_CONSOLE_MANUAL_ISSUE), we are encountering multiple errors where the events' database is locked. Upon reviewing the code, I found that we are not adhering to Room's [documentation guidelines](https://developer.android.com/training/data-storage/room#database). Specifically, As SID is creating multiple instances of the `EventRoomDatabase` object, whereas the documentation states that the …

[MS-936] Fix the db locked issue by Refactor EventDatabaseFactory to create a single instance of the event DB

---

feature/enrol-last-biometric/src/main/java/com/simprints/feature/enrollast/screen/EnrolLastBiometricFragment.kt
feature/enrol-last-biometric/src/main/java/com/simprints/feature/enrollast/screen/EnrolLastBiometricViewModel.kt
feature/enrol-last-biometric/src/main/java/com/simprints/feature/enrollast/screen/EnrolLastState.kt
feature/enrol-last-biometric/src/main/java/com/simprints/feature/enrollast/screen/usecase/CheckForDuplicateEnrolmentsUseCase.kt
feature/enrol-last-biometric/src/main/java/com/simprints/feature/enrollast/screen/usecase/HasDuplicateEnrolmentsUseCase.kt
feature/enrol-last-biometric/src/test/java/com/simprints/feature/enrollast/screen/EnrolLastBiometricViewModelTest.kt
feature/enrol-last-biometric/src/test/java/com/simprints/feature/enrollast/screen/usecase/CheckDuplicateEnrolmentsErrorsUseCaseTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-245)
Will be released in: **version**
* Updated the log level for cases when there are match responses during duplicate checks.
* Changed user-facing error message to be more generic in the same conditions, no more saying that there was a duplicate when we did not even match.

MS-245 Better enrol last error

---

feature/enrol-last-biometric/src/main/java/com/simprints/feature/enrollast/screen/usecase/BuildSubjectUseCase.kt
feature/matcher/src/test/java/com/simprints/matcher/usecases/FingerprintMatcherUseCaseTest.kt
infra/core/src/main/java/com/simprints/core/domain/fingerprint/FingerprintSample.kt
infra/enrolment-records/realm-store/src/main/java/com/simprints/infra/enrolment/records/realm/store/models/DbFingerprintSample.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/commcare/CommCareIdentityDataSource.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/local/models/DbFingerprintSample.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/remote/models/fingerprint/ApiFingerprintReference.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/remote/models/fingerprint/ApiFingerprintTemplate.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/commcare/CommCareIdentityDataSourceTest.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/local/EnrolmentRecordLocalDataSourceImplTest.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/local/models/DbSubjectTest.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/remote/EnrolmentRecordRemoteDataSourceImplTest.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/subject/biometricref/ApiBiometricReference.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/subject/biometricref/fingerprint/ApiFingerprintTemplate.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/SubjectFactory.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/models/subject/ApiEnrolmentRecordCreationEventTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/models/subject/ApiEnrolmentRecordMoveEventTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/models/subject/ApiEnrolmentRecordUpdateEventTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/SubjectFactoryTest.kt
infra/events/src/main/java/com/simprints/infra/events/event/domain/models/subject/EnrolmentRecordCreationEvent.kt
infra/events/src/main/java/com/simprints/infra/events/event/domain/models/subject/FingerprintTemplate.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-961)
Based on the [Slack discussion](https://simprints.slack.com/archives/G01B5GC5AH3/p1742801326612559), the `templateQualityScore` field is unnecessary and does not need to be stored in the records database.

[MS-961] Remove templateQualityScore from FingerprintSample 

---

infra/enrolment-records/realm-store/src/main/java/com/simprints/infra/enrolment/records/realm/store/config/RealmConfig.kt

Oops 😅... totally forgot to bump the Realm schema version after ditching DbFingerprintSample.templateQualityScore

[MS-961] [MS-961] Update Realm schema version to 17

---

feature/matcher/src/main/java/com/simprints/matcher/usecases/MatchResultSet.kt
feature/matcher/src/test/java/com/simprints/matcher/usecases/MatchResultSetTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-973)
When two subjects have the same confidence score during matching, only one is returned in the identification response. Please refer to the ticket for more details.
First known affected version: **All recent versions**
* Attached two videos one for the problem and the fix
*  Improve sorting logic in MatchResultSet to handle equal confidence scores by subject ID
* Use the project cGKXBnPkLGKtK0V2TUxo, which contains many duplicate ROCv3 and simatcher subjects, and verify that subjects with the same confidence score are all included in the identification results.
https://github.com/user-attachments/assets/889549ed-dbeb-4386-b411-a9fde9dae7e6 …

[MS-973] Fix sorting logic in MatchResultSet to handle equal confidence scores

---

gradle/libs.versions.toml
id/proguard-rules.pro
id/src/main/java/com/simprints/id/Application.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/EventDatabaseFactory.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/EventRoomDatabase.kt
infra/events/src/main/java/com/simprints/infra/events/event/local/migrations/EventMigration14to15.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-971)
* Bump sqlCipher-core from 4.5.4 to 4.7.2
* Updates Event Database to use new SQLCipher API.
* Addresses known vulnerabilities and strengthens encryption mechanisms.
* Optimizes database operations for faster execution.
*  Ensures better integration with newer platforms and tools.
This upgrade is backward-compatible with existing databases. However, it's recommended to test thoroughly to ensure seamless integration.
Verify that an event database encrypted with an older version of SQLCipher can be successfully opened using the latest version.

[MS-971] Bump sqlCipher-core from 4.5.4 to 4.7.2

---

feature/alert/README.md
feature/exit-form/README.md

[JIRA ticket](https://simprints.atlassian.net/browse/MS-580)
* `NavController::navigate` is already replaced with `NavController::navigateSafely` extension, but examples in `README` files remained. Updated them.
This is a small change in development-only docs.

[MS-580] Removing remaining NavController::navigate - from READMEs

---

infra/config-store/src/main/java/com/simprints/infra/config/store/ConfigRepositoryImpl.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/ConfigRepositoryImplTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-120)
Not user-facing, only affects logging:
When an API call for downloading a privacy notice occurs, and returns 404 (not found) - not logging this.

[MS-120] Skipping non-existent privacy notice download 404 logging

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/usecases/GetEnrolmentCreationEventForSubjectUseCase.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1007)
* Added a logged exception in case `subjectActions` are null when they shouldn't
* Describe how the reviewers can verify that issue is fixed

[MS-1007] Log an exception when subjectActions are null

---

feature/setup/src/main/java/com/simprints/feature/setup/screen/SetupViewModel.kt
feature/setup/src/test/java/com/simprints/feature/setup/screen/SetupViewModelTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-988)
Will be released in: **version**
* Only check for RankOne licence on Setup screen when it is actually configured.
* Missed a spot in the initial integration PR (wasn't able to check it before vulcan changes 🤦🏻 )

MS-988 Skip ROC license check on Setup screen if only SimFace is enabled for face

---

infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/local/RoomEnrolmentRecordLocalDataSource.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/local/RoomEnrolmentRecordLocalDataSourceTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1028)
First known affected version: **not yet released**
Current logic calculates pageSize = range.last - range.first, which skips the last item in the range when range.last == range.first + pageSize.
Update to:
pageSize = range.last - range.first + 1
to include the full range.
Normal identification shows that the number of identified subjects in each range is off by one, typically one less than expected.

[MS-1028] Fix pagination logic by adjusting pageSize calculation in RoomEnrolmentRecordLocalDataSource

---

infra/enrolment-records/realm-store/src/main/java/com/simprints/infra/enrolment/records/realm/store/RealmWrapperImpl.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1030)
First known affected version: **long time ago**
* After updating from SID 2025.1.0 to 2025.2.0, I accessed the troubleshooting screen before Realm completed its automatic migration from schema version 16 to 17.
* Since Realm was not yet initialized, each call tried to open the Realm with the same file but potentially conflicting schema states, leading to:
```
Fatal Exception: java.lang.IllegalStateException  
[RLM_ERR_MISMATCHED_CONFIG]: Realm at path ... already opened with different schema version
```
Added a Mutex to synchronize access to getRealm() and ensure that only one thread initializes the Realm instance. This prevents the crash and guarantees that the schema is applied only once.
* …

[MS-1030] Implement thread-safe access to Realm instance using Mutex

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/usecase/LogoutUseCase.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/logout/usecase/LogoutUseCaseTest.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/tools/di/FakeCoreModule.kt
infra/config-sync/src/main/java/com/simprints/infra/config/sync/ConfigManager.kt
infra/config-sync/src/test/java/com/simprints/infra/config/sync/ConfigManagerTest.kt
infra/core/src/main/java/com/simprints/core/CoreModule.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/local/migration/RealmToRoomMigrationFlagsStore.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/local/migration/RealmToRoomMigrationFlagsStoreTest.kt
infra/sync/src/main/java/com/simprints/infra/sync/SyncModule.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1032)
* Added logic to schedule the DB migration worker after project config refresh. This ensures the migration can run without requiring an app restart.
* Previously, the migration was only scheduled in Application.onCreate(), which doesn’t run unless the app is restarted. This change ensures migrations can be triggered proactively.
* Verify that the DB migration worker is scheduled after a config refresh

[MS-1032] Schedule Realm to Room migration on project config refresh

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/main/sync/SyncViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/about/AboutViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModel.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/main/sync/SyncViewModelTest.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/about/AboutViewModelTest.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModelTest.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManager.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManagerImpl.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/EventSyncManagerTest.kt
infra/sync/src/main/java/com/simprints/infra/sync/config/usecase/HandleProjectStateUseCase.kt
infra/sync/src/test/java/com/simprints/infra/sync/config/usecase/HandleProjectStateUseCaseTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1037)
First known affected version: **2025.2.0**
* When implementing record update we added a new schema version of enrolment events, but did not add the new type to be counted for upload.
* Count both types of enrolment event versions in the sync info screen.
* Simplify the count method for "all" events by removing the optional type argument that is never provided. If it is needed in the future, the new list argument version can be used instead.
* Do a couple of enrolments (without sync)
* Check sync info screen, the "Records to Upload" should not be 0.

MS-1037 Also count enrolment v4 for record upload counter in sync info

---

infra/core/src/main/java/com/simprints/core/tools/utils/LanguageHelper.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/EnrolmentRecordRepositoryImpl.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/EnrolmentRecordRepositoryImplTest.kt
infra/network/build.gradle.kts
infra/network/src/main/java/com/simprints/infra/network/url/BaseUrlProviderImpl.kt
infra/network/src/test/java/com/simprints/infra/network/url/BaseUrlProviderImplTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-122)
* Moving a couple of remaining cases of shared prefs usage to the encrypted counterpart to avoid accidentally leaking some IDs/domain. The risk was always very low, but this ticket has been in the backlog for too long by now.
* Did not move the language helper since it is fine as-is (it stores only the language code), and the performance penalty from encryption might affect app startup times. 
* Use the app as usual - upsync progress should be reported correctly.

MS-122 Secure prefs everywhere

---

infra/sync/src/main/java/com/simprints/infra/sync/config/usecase/ResetLocalRecordsIfConfigChangedUseCase.kt
infra/sync/src/main/java/com/simprints/infra/sync/config/worker/ProjectConfigDownSyncWorker.kt
infra/sync/src/test/java/com/simprints/infra/sync/config/usecase/ResetLocalRecordsIfConfigChangedUseCaseTest.kt
infra/sync/src/test/java/com/simprints/infra/sync/config/worker/ProjectConfigDownSyncWorkerTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-997)
Will be released in: **version**
First known affected version: **2025.1.0**
* When sync partitioning changes in the project configuration, already downloaded records remain in the local database, causing a mismatch in numbers.
* Additional local records might also affect the matching speed and results by returning records that shouldn't have been synced (if the ID pool type does not match sync partitioning).
* On the project configuration sync, if the change in sync partitioning has been detected, all local records are wiped, and a new sync is scheduled.
* Change of sync partitioning is an extraordinary circumstance, and some disruption should be expected. Creating more complex diff handling is possible, but the ROI would not be …

MS-997 Reset local records when sync partitioning changes

---

infra/network/src/main/java/com/simprints/infra/network/url/BaseUrlProviderImpl.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-122)
First known affected version: **2025.3.0**
* On a fresh install, there is no URL in the legacy prefs and no default value was provided.
* Add default value when attempting to read value from the legacy URL prefs.
* Have a fresh install. Try to log in.

Provide default base url if is none in the legacy prefs

---

feature/login-check/src/main/java/com/simprints/feature/logincheck/usecases/ReportActionRequestEventsUseCase.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/callout/ApiCalloutPayload.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/callout/ApiConfirmationCallout.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/EventValidationUtils.kt
infra/events/src/debug/java/com/simprints/infra/events/sampledata/EventFactoryUtils.kt
infra/events/src/main/java/com/simprints/infra/events/event/domain/models/callout/ConfirmationCalloutEvent.kt
infra/events/src/test/java/com/simprints/infra/events/event/domain/models/EventPayloadTest.kt
infra/events/src/test/java/com/simprints/infra/events/event/domain/models/callout/ConfirmationCalloutEventTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1065)
* The `ConfirmationCalloutEventV3` class now contains `metadata: String?` field 
* This field already exists in the confirmation callout request, and now is passed to the event
* The `metadata` field is now also passed to the BFSID
* Send the `metadata=test` field for the `com.simprints.id.CONFIRM_IDENTITY` request. Use the `Custom Intent` screen within the Intent Launcher app for that.

[MS-1065] Adding 'metadata' field to the ConfirmationCalloutEventV3

---

feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/overview/OverviewFragment.kt
feature/troubleshooting/src/main/res/layout/fragment_troubleshooting_overview.xml
infra/logging/src/main/java/com/simprints/infra/logging/SimberBuilder.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1060)
First known affected version: **2025.1.0**
* Log writer internally references Java 8 time API which is only available starting from Android 8. This causes NoClassDefFoundError exception on app start.
* Only initialise the log writer starting from Android 8 (API 26)
* Install the release build of the app on Android 7 device - it should work, file logs should not be available.
* Do the same on Android 8 - file logs should be available.

Disable file log writer on per-oreo Android versions

---

feature/troubleshooting/src/main/java/com/simprints/feature/troubleshooting/recordsmigration/RealmToRoomRecordsMigrationViewModel.kt
feature/troubleshooting/src/test/java/com/simprints/feature/troubleshooting/reordsmigration/RealmToRoomRecordsMigrationViewModelTest.kt
infra/logging/src/main/java/com/simprints/infra/logging/ExcludedFromGeneratedTestCoverageReports.kt
infra/logging/src/main/java/com/simprints/infra/logging/SimberBuilder.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1069)
First known affected version: **2025.2.0**
* Try to access the troubleshooting screen before login the app will crash as the database is not yet initialized. 
* There’s no longer a need to check the database migration status before login, as it depends heavily on the specific project. 
* Describe how the reviewers can verify that issue is fixed

Hide DB info from troubleshooting screen when user isn't logged in

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/usecases/DeleteSessionEventsIfNeededUseCase.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/usecases/DeleteSessionEventsIfNeededUseCaseTest.kt

[JIRA ticket]()
First known affected version: **2025.2.0?**
* When the project is in ending or paused state, sessions are still being kep,t which can result in an "alert-only" session being uploaded on the final sync attempt from the device.
* When returning error response from the app, delete any session events if the project is not in the RUNNING state.
* Create a project, create some sessions, mark the project as ending, update the config on the device, but do not up-sync the data. 
* Try running some workflows and wait until the upsync.

Do not keep sessions if project is paused or ended

---

infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManagerImpl.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/master/EventSyncMasterWorker.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/EventSyncManagerTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-976)
First known affected version: **2024.1.0**
* There was a discrepancy in the number of requests and upsynced events for those requests.
* Turns out we forgot to properly close event scopes. 
* Added scope closing after subject request.
* Also force-close all existing down sync in the worker before creating a new one.

MS-976 Close event scope after down-syncing a single subject

---

.aiexclude

* According to the Gemini doc, this file works similarly to gitignore, but for the AI code generators ingesting the contents of the repo.
* This is something we should have done before any bots on the code, but better later than never.

Add AI exclusions file according to best practices

---

id/src/main/java/com/simprints/id/Application.kt
infra/logging/build.gradle.kts
infra/logging/src/main/java/com/simprints/infra/logging/LoggingConstants.kt
infra/logging/src/main/java/com/simprints/infra/logging/usecases/UpdateAndGetVersionHistoryUseCase.kt
infra/logging/src/test/java/com/simprints/infra/logging/usecases/UpdateAndGetVersionHistoryTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-109)
* On process start, adds version update history to custom analytics fields.
* Only tracking within the "update" flows and not across re-installs since this custom field is aimed at helping with the version migration.
* Run some flows, check the logs for the user properties.

MS-109 Add custom field for installed version history tracking

---

feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/FetchSubjectContract.kt
feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/FetchSubjectParams.kt
feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/screen/FetchSubjectFragment.kt
feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/screen/FetchSubjectViewModel.kt
feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/screen/usecase/FetchSubjectUseCase.kt
feature/fetch-subject/src/test/java/com/simprints/feature/fetchsubject/screen/FetchSubjectViewModelTest.kt
feature/fetch-subject/src/test/java/com/simprints/feature/fetchsubject/screen/usecase/FetchSubjectUseCaseTest.kt
feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCase.kt
infra/core/src/main/java/com/simprints/core/tools/utils/ExtractCommCareCaseIdUseCase.kt
infra/core/src/test/java/com/simprints/core/tools/utils/ExtractCommCareCaseIdUseCaseTest.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/EnrolmentRecordsStoreModule.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/commcare/CommCareIdentityDataSource.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/commcare/CommCareIdentityDataSourceTest.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManager.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManagerImpl.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/commcare/CommCareEventDataSource.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/down/domain/RemoteEventQuery.kt
infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/CommCareEventSyncTask.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/EventSyncManagerTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/commcare/CommCareEventDataSourceTest.kt
infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/CommCareEventSyncTaskTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1091)
* Adds the ability to sync specific caseIds from CommCare
* `EventSyncManagerImpl` makes use of this to downsync individual subjects "on-demand" (used during verification to guarantee that the biometrics of the subject we are matching against are present on the device)
* This is achieved by passing metadata (which should contain the caseId associated with the subject we want to verify) from `FetchSubject*` to `EventSyncManagerImpl` which tries to parse and extract the caseId
* Since the parsing and extracting bit (as small as it is) was shared with `CommCareIdentityDataSource` (used for the same use case but when just-in-time CommCare reading is configured) - it was extracted in a common use …

[MS-1091] Handle fetching specific caseIds from CommCare

---

face/capture/src/main/java/com/simprints/face/capture/screens/livefeedback/LiveFeedbackFragment.kt

[JIRA ticket]()
First known affected version: **2025.3.0**
* When a live-feedback fragment is created, it does not have access to the context; therefore, `requireContext()` fails.
* Ensured that `requireContext` is not called in the fragment construction
* Do some face captures

Do not require context on fragment creation since it is not attached

---

feature/client-api/src/main/java/com/simprints/feature/clientapi/mappers/response/LibSimprintsResponseMapper.kt
feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/response/LibSimprintsResponseMapperTest.kt
gradle/libs.versions.toml

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1137)
* Adds deviceId and appVersionName to LibSimprints responses in the same way as it is done for CommCare responses
* Do some calls with the updated version of intents launcher

MS-1137 Add device ID and app version to LibSimprints responses

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/usecase/LogoutUseCase.kt
feature/dashboard/src/test/java/com/simprints/feature/dashboard/logout/usecase/LogoutUseCaseTest.kt
infra/enrolment-records/realm-store/src/main/java/com/simprints/infra/enrolment/records/realm/store/RealmWrapper.kt
infra/enrolment-records/realm-store/src/main/java/com/simprints/infra/enrolment/records/realm/store/RealmWrapperImpl.kt
infra/enrolment-records/realm-store/src/test/java/com/simprints/infra/enrolment/records/realm/store/RealmWrapperImplTest.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/EnrolmentRecordRepositoryImpl.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/local/EnrolmentRecordLocalDataSource.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/local/RealmEnrolmentRecordLocalDataSource.kt
infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/local/RoomEnrolmentRecordLocalDataSource.kt
infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/local/RoomEnrolmentRecordLocalDataSourceTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1061)
First known affected version: **It’s been a long time since we started using Realm DB**
* Check the Jira ticket regarding the issue where, after a user logs out from one project and logs into another, Realm reuses the same db file, causing the user to lose some of the previously synced records.
* Now, when logging out, SID closes the active DB connection, forces the creation of a new Realm file when relogin, and resolves the problem. As shown in this screenshot, two DB files are created—one for the old project and another for the new one—so there’s no need to delete the old file.
* Follow the steps n the jira ticket to make sure that the issue is resolved.

[MS-1061] Fix relogin issue

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfo.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/usecase/ObserveSyncInfoUseCase.kt
feature/dashboard/src/main/res/navigation/graph_dashboard.xml
feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModelTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1158)
First known affected version: **2025.3.0**
* When the device is compromised, the user is logged out and local data is cleared. This causes a crash when any part of the UI attempts to request the project state.
* Added handling for the exception that is thrown in the AuthManager when there is no Firebase token available. ([We should really look into how we are handling missing project info throughout the app](https://simprints.atlassian.net/browse/MS-1006?focusedCommentId=35165)) 
* Added explicit handling of forced logout in the sync screen similar to how it was before Sync refactor.
* Log into the project, do some workflows
* In Vulcan, mark the device as compromised
* In SID, navigate to …

MS-1158 Compromised logout fix

---

feature/dashboard/src/main/java/com/simprints/feature/dashboard/base/BaseFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/LogoutSyncViewModel.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/sync/LogoutSyncFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/syncdecline/LogoutSyncDeclineFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/usecase/LogoutUseCase.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/about/AboutFragment.kt
feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModel.kt
feature/dashboard/src/main/res/navigation/graph_dashboard.xml
feature/dashboard/src/test/java/com/simprints/feature/dashboard/logout/sync/LogoutSyncFragmentTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1188)
First known affected version: **2025.3.0**
* Compounded issue that leads to some racing:
* In both cases, the logout use case is called in the view model-scoped coroutine. Navigation happens right after the start of the logout coroutine, which kills the VM scope and cancels the logout navigation (sometimes, this is the racing part).
* Navigation to the root leads to checking for "logged in"  state (which succeeds if navigation happened faster than the data cleanup) and opens the dashboard instead of the "login request" placeholder.
* Made logout use case blocking (while still executing on the IO dispatcher) to block navigation until the data cleanup is done.
* Minor cleanup of the navigation …

MS-1188 Short-term logout fix

---

feature/matcher/build.gradle.kts
feature/matcher/src/main/java/com/simprints/matcher/screen/MatchFragment.kt
feature/matcher/src/main/res/navigation/graph_matcher.xml

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1181)
* Since the user can now get stuck on the matching screen when there is no CommCare permission the back press should be handled in the same way it is handled on other screens.
* Make sure that SID does not have CommCare permission.
* Start the workflow, capture biometrics and move to the matching.
* When presented with permission requests - reject all and press (gesture) back from the matching screen.

MS-1181 Exit form handling on matcher screen

---

feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCaseTest.kt
infra/config-store/src/main/java/com/simprints/infra/config/store/models/ProjectConfiguration.kt
infra/config-store/src/test/java/com/simprints/infra/config/store/models/ProjectConfigurationTest.kt

[JIRA ticket](https://simprints.atlassian.net/browse/MS-1194)
Will be released in: **2025.4.0**
* When testing the SimFace integration, I noticed that the age group configurations were being ignored.
* Now the allowed age groups are enabled for the SimFace SDK
* change the age limits for SimFace SDk then the age group selection screen will appear

[MS-1194] Add support for simFace allowed age range in ProjectConfiguration
