Simprints/Android-Simprints-ID

- fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModel.kt
- fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/screen/FingerprintCaptureViewModelTest.kt
- fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintCaptureWrapperV1.kt
- fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/capture/FingerprintCaptureWrapperV2.kt
- fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/exceptions/safe/NoFingerDetectedException.kt
* Reporting the exceptions as non-fatal in crashlytics
* Added a different message for each instance of the exception
> CORE-2071 Better NoFingerDetectedException reporting

- infra/core/src/main/java/com/simprints/core/tools/utils/SimNetworkUtilsImpl.kt
- infra/core/src/test/java/com/simprints/core/tools/utils/SimNetworkUtilsImplTest.kt
Using `NetworkCapabilities.NET_CAPABILITY_INTERNET` followed by `NetworkCapabilities.NET_CAPABILITY_VALIDATED`.
> [MS-28] Internet availability & validation checks in SimNetworkUtilImpl

- feature/alert/src/main/java/com/simprints/feature/alert/screen/AlertFragment.kt
- feature/client-api/src/main/java/com/simprints/feature/clientapi/mappers/response/CommCareResponseMapper.kt
- feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/response/CommCareResponseMapperTest.kt
Currently pointing to release/2023.4.0 but will change to release/2023.4.1 once the branch is ready.
> Fix CommCare IDENTIFY response

- infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepository.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepositoryTest.kt
A hotfix for `release/2023.3.4`.
> [CORE-3225] Down-sync unwanted exception on userId fixed for non-user sync

- feature/login-check/src/main/java/com/simprints/feature/logincheck/LoginCheckViewModel.kt
- feature/login-check/src/main/java/com/simprints/feature/logincheck/usecases/UpdateStoredUserIdUseCase.kt
- feature/login-check/src/test/java/com/simprints/feature/logincheck/LoginCheckViewModelTest.kt
- feature/login-check/src/test/java/com/simprints/feature/logincheck/usecases/UpdateStoredUserIdUseCaseTest.kt
- infra/auth-logic/src/main/java/com/simprints/infra/authlogic/authenticator/Authenticator.kt
- infra/auth-store/src/main/java/com/simprints/infra/authstore/AuthStore.kt
- infra/auth-store/src/main/java/com/simprints/infra/authstore/AuthStoreImpl.kt
- infra/auth-store/src/main/java/com/simprints/infra/authstore/domain/LoginInfoStore.kt
- infra/auth-store/src/test/java/com/simprints/infra/authstore/AuthStoreImplTest.kt
- infra/auth-store/src/test/java/com/simprints/infra/authstore/domain/LoginInfoStoreTest.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepository.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepositoryTest.kt
Cherry-picked contents of #545 onto the release branch.
> MS-201 Save user ID on login/flow to correctly sync user-scoped data

- feature/login-check/src/test/java/com/simprints/feature/logincheck/usecases/StartBackgroundSyncUseCaseTest.kt
- id/src/main/java/com/simprints/id/Application.kt
- id/src/main/java/com/simprints/id/ScheduleBackgroundSyncUseCase.kt
- id/src/test/java/com/simprints/id/ScheduleBackgroundSyncUseCaseTest.kt
- infra/config-store/src/main/java/com/simprints/infra/config/store/local/ConfigLocalDataSourceImpl.kt
- infra/config-store/src/main/java/com/simprints/infra/config/store/local/migrations/models/OldProjectConfig.kt
- infra/config-store/src/main/java/com/simprints/infra/config/store/local/models/UpSynchronizationConfiguration.kt
- infra/config-store/src/main/java/com/simprints/infra/config/store/models/ProjectConfiguration.kt
- infra/config-store/src/main/java/com/simprints/infra/config/store/models/UpSynchronizationConfiguration.kt
- infra/config-store/src/main/java/com/simprints/infra/config/store/remote/models/ApiSynchronizationConfiguration.kt
- infra/config-store/src/main/proto/project_config.proto
- infra/config-store/src/test/java/com/simprints/infra/config/store/models/ProjectConfigurationTest.kt
- infra/config-store/src/test/java/com/simprints/infra/config/store/testtools/Models.kt
- infra/config-sync/src/main/java/com/simprints/infra/config/sync/usecase/RescheduleWorkersIfConfigChangedUseCase.kt
- infra/config-sync/src/main/java/com/simprints/infra/config/sync/worker/ProjectConfigDownSyncWorker.kt
- infra/config-sync/src/test/java/com/simprints/infra/config/sync/testtools/Models.kt
- infra/config-sync/src/test/java/com/simprints/infra/config/sync/usecase/RescheduleWorkersIfConfigChangedUseCaseTest.kt
- infra/config-sync/src/test/java/com/simprints/infra/config/sync/worker/ProjectConfigDownSyncWorkerTest.kt
- infra/core/src/main/java/com/simprints/core/CoreModule.kt
- infra/images/src/main/java/com/simprints/infra/images/ImageUpSyncScheduler.kt
- infra/images/src/main/java/com/simprints/infra/images/worker/ImageUpSyncSchedulerImpl.kt
- infra/images/src/test/java/com/simprints/infra/images/worker/ImageUpSyncSchedulerImplTest.kt
Notable changes:
* Added the flag to the project config
* Added a way to reschedule certain workers when the project config changed.
> MS-204 Restrict image upload to unmetered connection if required by config

- feature/consent/src/main/java/com/simprints/feature/consent/screens/consent/helpers/GeneralConsentTextHelper.kt
- feature/consent/src/main/java/com/simprints/feature/consent/screens/consent/helpers/ParentalConsentTextHelper.kt
- feature/consent/src/test/java/com/simprints/feature/consent/screens/consent/helpers/GeneralConsentTextHelperTest.kt
- feature/consent/src/test/java/com/simprints/feature/consent/screens/consent/helpers/ParentalConsentTextHelperTest.kt
Sentences were concatenated without spaces separating them.
> [MS-216] Consent text missing spaces - fix

- feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/ExecutionTracker.kt
- feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorActivity.kt
- feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorFragment.kt
- feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt
- feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/cache/OrchestratorCache.kt
- feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/ExecutionTrackerTest.kt
* @BurningAXE, added handling of the case you asked in the previous PR
* @alexandr-simprints, added a fix for the issue you found - should have included activity life cycle tracking in the first place, tbh.
> Fun with flags

- feature/dashboard/src/main/res/layout/fragment_sync_info.xml
"Select modules" is missing for some reason
> Fix missing module selection button

- build-logic/build_properties.gradle.kts
- infra/core/src/main/java/com/simprints/core/tools/time/Timestamp.kt
This PR fixes the staging builds in main branch
> Keep timestamp

- fingerprint/connect/src/main/java/com/simprints/fingerprint/connect/screens/issues/nfcpair/NfcPairFragment.kt
I have no comments for this fix 🤷🏻
> MS-259 Do not open serial entry when finishing NFC connection

- infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/EventRemoteDataSource.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/EventRemoteInterface.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/up/tasks/EventUpSyncTask.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/EventValidationUtils.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/ApiEventTest.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/remote/EventRemoteDataSourceTest.kt
- infra/events/src/main/java/com/simprints/infra/events/event/domain/models/callback/ConfirmationCallbackEvent.kt
- infra/events/src/main/java/com/simprints/infra/events/event/domain/models/callback/EnrolmentCallbackEvent.kt
- infra/events/src/main/java/com/simprints/infra/events/event/domain/models/callback/ErrorCallbackEvent.kt
- infra/events/src/main/java/com/simprints/infra/events/event/domain/models/callback/RefusalCallbackEvent.kt
- infra/network/src/main/java/com/simprints/infra/network/httpclient/DefaultOkHttpClientBuilder.kt
* Align callback errors
* Do not try to upload in batches of 0
* Fix issue with HEAD request definition
> MS-267 Sync integration fixes (batch 1)

- infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepository.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepositoryTest.kt
Same as #653 but for the next release.
> RF-427 User ID fix cherry-pick 

- infra/resources/src/main/res/values-am-rET/strings.xml
- infra/resources/src/main/res/values-am/strings.xml
- infra/resources/src/main/res/values-bn/strings.xml
This branch was made to keep track of translation commits applied to the main from Transifex after the release branch has been officially started. It should be merged only after all the operational languages are marked 100% verified in Transifex.
> Translation cherry-picking

- feature/login/src/main/res/layout/fragment_login_form.xml
> [MS-452] 'change backend url' link no longer overlaps the login button

- feature/login/src/main/res/layout/fragment_login_form.xml
> [MS-560] Login screen buttons are now the same width as input fields

- fingerprint/capture/src/main/res/layout-land/fragment_finger.xml
- fingerprint/capture/src/main/res/layout-land/fragment_fingerprint_capture.xml
> [MS-561] Fingerprint capture image is now split into two columns

- face/capture/src/main/res/layout-land/fragment_preparation.xml
- face/capture/src/main/res/values/dimens.xml
> [MS-555] Adding landscape support for the preparation fragment

- gradle/libs.versions.toml
This reverts commit e2ab1fbc5d0f32c82436137d83c776d30648e7d6, reversing changes made to 03b2bf85d4588e4c7b92c72045716782801ece11.
> Revert protobuf version update

- feature/client-api/src/main/java/com/simprints/feature/clientapi/mappers/request/IntentToActionMapper.kt
- feature/client-api/src/test/java/com/simprints/feature/clientapi/mappers/request/IntentToActionMapperTest.kt
- feature/orchestrator/src/main/AndroidManifest.xml
Cherry-picking of session ID fix/hack that was applied on 2024.1.5
> Session ID fix backport

- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/LibraryHiltConventionPlugin.kt
- build-logic/convention/src/main/kotlin/LibraryProtobufConventionPlugin.kt
- build-logic/convention/src/main/kotlin/LibraryRoomConventionPlugin.kt
- build-logic/convention/src/main/kotlin/common/DependencyExt.kt
- build.gradle.kts
- gradle/libs.versions.toml
According to the reported issue , Hilt does not currently support KSP: https://github.com/google/dagger/issues/4429
> [MS-732] address hilt and ksp compatibility issue

- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/LibraryHiltConventionPlugin.kt
- build-logic/convention/src/main/kotlin/LibraryProtobufConventionPlugin.kt
- build-logic/convention/src/main/kotlin/LibraryRoomConventionPlugin.kt
- build-logic/convention/src/main/kotlin/common/DependencyExt.kt
- build.gradle.kts
- gradle/libs.versions.toml
Reverts Simprints/Android-Simprints-ID#914
> Revert "[MS-732] address hilt and ksp compatibility issue"

- feature/exit-form/src/main/java/com/simprints/feature/exitform/ExitFormConfigurationBuilder.kt
- feature/exit-form/src/main/java/com/simprints/feature/exitform/config/ExitFormOption.kt
- feature/exit-form/src/main/java/com/simprints/feature/exitform/screen/ExitFormFragment.kt
- feature/exit-form/src/main/res/layout-land/fragment_exit_form.xml
- feature/exit-form/src/main/res/layout/fragment_exit_form.xml
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/remote/models/ApiRefusalPayload.kt
- infra/events/src/main/java/com/simprints/infra/events/event/domain/models/RefusalEvent.kt
- infra/resources/src/main/res/values/strings.xml
(cherry picked from commit cf471dca0e972f163589ee188c1f2894131fb9c3)
> [MS-710] Add UNCOOPERATIVE_CHILD exit option

- infra/resources/src/main/res/values-am-rET/strings.xml
- infra/resources/src/main/res/values-am/strings.xml
- infra/resources/src/main/res/values-bn/strings.xml
- infra/resources/src/main/res/values-fr/strings.xml
- infra/resources/src/main/res/values-hi/strings.xml
A cherry-pick of the last five commits from Transfix.
> Update translations 2024.2.1

- fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/screen/ObserveFingerprintScanStatusUseCase.kt
- fingerprint/capture/src/test/java/com/simprints/fingerprint/capture/screen/ObserveFingerprintScanStatusUseCaseTest.kt
- fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/tools/accumulator/ByteArrayAccumulator.kt
- fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/wrapper/ScannerWrapper.kt
- fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/wrapper/ScannerWrapperV1.kt
- fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/wrapper/ScannerWrapperV2.kt
- fingerprint/infra/scanner/src/test/java/com/simprints/fingerprint/infra/scanner/wrapper/ScannerWrapperV2Test.kt
- Improved LED control logic for increased performance and reliability by eliminating an unnecessary call to the "set LEDs off" function.
- Rename turnFlashingOrangeLeds to turnFlashingWhiteLeds
> Improve led control logic

- infra/resources/src/main/res/values-fr/strings.xml
- infra/resources/src/main/res/values/strings.xml
Cherry-picking the latest changes in localisation
> Translations backport

- infra/enrolment-records-store/src/main/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSource.kt
- infra/enrolment-records-store/src/test/java/com/simprints/infra/enrolment/records/store/commcare/CommCareIdentityDataSourceTest.kt
Modify CommCareIdentityDataSource to retrieve enrollment records according to the template format.
> [MS-797] Update CommCareIdentityDataSource to return enrollment recods based on template format

- feature/dashboard/build.gradle.kts
- feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/OverviewFragment.kt
- feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/OverviewViewModel.kt
- feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/usecase/CollectScannerStateUseCase.kt
- feature/dashboard/src/main/res/layout/fragment_troubleshooting_overview.xml
- feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/OverviewViewModelTest.kt
- feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/troubleshooting/overview/usecase/CollectScannerStateUseCaseTest.kt
* Basic vero information (id, versions, charge) on the overview screen
> MS-805 Vero information in troubleshooting overview

- feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/OrchestratorViewModel.kt
- feature/orchestrator/src/test/java/com/simprints/feature/orchestrator/OrchestratorViewModelTest.kt
* Applying the previous fix in full.
> Cherry-pick to release: [MS-790] Add follow-up steps to session steps instead of replacing them

- .github/workflows/deploy-main-workflow.yml
Context of request from Jon here: https://simprints.slack.com/archives/GAW460V19/p1736868512985299
> Add deploying a debug build to FB on main push

- fingerprint/capture/src/main/java/com/simprints/fingerprint/capture/views/fingerviewpager/FingerFragment.kt
- fingerprint/capture/src/main/res/layout-land/fragment_finger.xml
- fingerprint/capture/src/main/res/layout-sw600dp-land/fragment_finger.xml
- fingerprint/capture/src/main/res/layout/fragment_finger.xml
Adding circular loading indicator that becomes visible during the image transfer
https://github.com/user-attachments/assets/42c8caa4-842f-4208-809e-92630f893ae6
https://github.com/user-attachments/assets/d3cfe4b8-b979-4d3f-bb02-afc8767a6f3d
> Adding progress indicator for image transfer

- fingerprint/capture/src/main/res/layout-sw600dp-land/fragment_finger.xml
- fingerprint/capture/src/main/res/layout-sw600dp-land/fragment_fingerprint_capture.xml
https://github.com/user-attachments/assets/8feba332-60a8-431b-9786-8ec0191d7682
> [MS-873] Wrapping content of the fingerprint capture in landscape mode so that all elements are always visible

- face/infra/bio-sdk-resolver/src/release/java/com/simprints/face/infra/biosdkresolver/ResolveSimFaceVersionUseCase.kt
- face/infra/bio-sdk-resolver/src/release/java/com/simprints/face/infra/biosdkresolver/SimFaceBioSdk.kt
> Fix imports in release builtType stubs of SimFace integration

- feature/matcher/src/main/java/com/simprints/matcher/screen/MatchViewModel.kt
- feature/matcher/src/test/java/com/simprints/matcher/screen/MatchViewModelTest.kt
[JIRA ticket](https://simprints.atlassian.net/browse/MS-124)
* Use decision policy to count very good/good/fair matches on the match screen.
* The hardcoded values were kept to have some kind of fallback, but realistically those should never be used.
* Setup reasonable decision policies per SDK (e.g. 20/50/90 for SimFace).
* Run identifications with known and unknown faces - the amounts of very good/good matches should match the confidence band counts in the result.
> MS-124 Use decision policy to determine very good/good/fair matches

- infra/enrolment-records/repository/build.gradle.kts
- infra/enrolment-records/repository/src/androidTest/AndroidManifest.xml
- infra/enrolment-records/repository/src/androidTest/kotlin/com/simprints/infra/enrolment/records/repository/local/HiltTestRunner.kt
- infra/enrolment-records/repository/src/androidTest/kotlin/com/simprints/infra/enrolment/records/repository/local/RealmEnrolmentRecordLocalDataSourceIntegrationTest.kt
[JIRA ticket](https://simprints.atlassian.net/browse/MS-1133)
* Added Android tests to validate Realm DB integration. These tests will help ensure functionality remains intact when updating to a different Realm version.
* Run the tests in an emulator or a physical device
> [MS-1133] Add androidTests for Realm Integration in SID

- feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/FetchSubjectContract.kt
- feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/FetchSubjectParams.kt
- feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/screen/FetchSubjectFragment.kt
- feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/screen/FetchSubjectViewModel.kt
- feature/fetch-subject/src/main/java/com/simprints/feature/fetchsubject/screen/usecase/FetchSubjectUseCase.kt
- feature/fetch-subject/src/test/java/com/simprints/feature/fetchsubject/screen/FetchSubjectViewModelTest.kt
- feature/fetch-subject/src/test/java/com/simprints/feature/fetchsubject/screen/usecase/FetchSubjectUseCaseTest.kt
- feature/orchestrator/src/main/java/com/simprints/feature/orchestrator/usecases/steps/BuildStepsUseCase.kt
- infra/core/src/main/java/com/simprints/core/tools/utils/ExtractCommCareCaseIdUseCase.kt
- infra/core/src/test/java/com/simprints/core/tools/utils/ExtractCommCareCaseIdUseCaseTest.kt
- infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/EnrolmentRecordsStoreModule.kt
- infra/enrolment-records/repository/src/main/java/com/simprints/infra/enrolment/records/repository/commcare/CommCareIdentityDataSource.kt
- infra/enrolment-records/repository/src/test/java/com/simprints/infra/enrolment/records/repository/commcare/CommCareIdentityDataSourceTest.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManager.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/EventSyncManagerImpl.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/event/commcare/CommCareEventDataSource.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/status/down/domain/RemoteEventQuery.kt
- infra/event-sync/src/main/java/com/simprints/infra/eventsync/sync/down/tasks/CommCareEventSyncTask.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/EventSyncManagerTest.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/event/commcare/CommCareEventDataSourceTest.kt
- infra/event-sync/src/test/java/com/simprints/infra/eventsync/sync/down/tasks/CommCareEventSyncTaskTest.kt
Copy of https://github.com/Simprints/Android-Simprints-ID/pull/1327 which I accidentally merged in base branch instead of `main`
> [MS-1091] Handle fetching specific caseIds from CommCare

- infra/enrolment-records/repository/src/androidTest/kotlin/com/simprints/infra/enrolment/records/repository/local/RealmEnrolmentRecordLocalDataSourceIntegrationTest.kt
Just fixing the instrumented test.
> Fix realm data source integration test

- feature/dashboard/src/main/java/com/simprints/feature/dashboard/logout/LogoutSyncViewModel.kt
- feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModel.kt
- feature/dashboard/src/main/java/com/simprints/feature/dashboard/settings/syncinfo/usecase/ObserveSyncInfoUseCase.kt
- feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/syncinfo/SyncInfoViewModelTest.kt
- feature/dashboard/src/test/java/com/simprints/feature/dashboard/settings/syncinfo/usecase/ObserveSyncInfoUseCaseTest.kt
[JIRA ticket](https://simprints.atlassian.net/browse/MS-419)
* Non-running projects don't display down-sync counters
* Fix: Logout screen doesn't show the sync button while the pre-logout sync is carried out automatically
> [MS-419] Sync new UI: project state fix

- face/infra/bio-sdk-resolver/src/release/java/com/simprints/face/infra/biosdkresolver/SimFaceBioSdk.kt
- face/infra/bio-sdk-resolver/src/staging/java/com/simprints/face/infra/biosdkresolver/SimFaceBioSdk.kt
* Updating the stub implementations of SimFace bio-sdk in non-debug variants to be able to build them
> Update SimFace build variants to the new interface
